### ISSUE TITLE
Lets discuss the way of atomic reading the values of tied gauges.

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [dropwizard/metrics#1016]
**Introduction:**
At the moment, the Gauge is the only one possible way to add unknown metric to register. It is suitable for cases of trivial monitoring structures, when one gauge exactly represents the whole state of monitoring structure(metric). But what I should do for cases when metric has complex state which described by multiple tied characteristics? The answer is easy, I should add multiple Gauges, one per each characteristic of complex metric. And the two kind of problems becomes: non-atomic reading and non-effective reading(the first is the cause of second).  For example when metric described by two gauges, the value of first gauge can be changed while reporter extracts the value of second, as result we can observe strange results for logically coupled metrics. The non-atomic reading, also can lead to non-effective reading when value from both first and second gauge should be taken from same "snapshot", and snapshot extraction is expensive. When snapshot is expensive, then reporter will waste CPU cycles to extract snapshot again. 
Moreover, the non-atomic reading problem affects both types of reporters "pull"(like JmxReporter) and "push"(like GraphiteReporter).

**The real world example of non-atomicity read problem:**
For example, currently I am implementing the [top](https://github.com/vladimir-bukhtoyarov/metrics-core-hdr/blob/1.6/src/main/java/com/github/metricscore/hdr/top/Top.java) for slow queries. When user creates the top with 10 positions, I will need to add 20 Gauges to registry(10 for latencies and 10 for queries descriptions). And for example the GraphiteReporter(and any other) can write the absolute mess to the monitoring database, because too many things can be changed during iteration of 20 gauges.
I'm sure that I'm not alone with this problem, and the other guys are faced with this during integration of  complex monitoring structures into metrics-core. 

**Workaround**
Snapshot(state) caching. That is what I exactly do in absence of native solution inside metrics-core library.
But caching leads to problems by itself. Caching does not provide 100% guarantee that value of coupled gauges will be taken from same snapshot, for example 2 second caching duration can be exceeded by long full GC pause.  Secondly, the caching adds unwanted coupling with reporter frequency, reporter is unable to observe fresh values with rate which less then caching period.

**My proposals of solving problem**
- Introduce GaugeGroup concept as first class citizen. 
  GaugeGroup will be an interface with two methods:

``` java
public interface GaugeGroup {

      // The name of each child gauge should be unique for particular GaugeGroup, but not by MetricRegistry
      Set<String> getGaugeNames();

      // the key is gauge name, the value is gauge value
      Map<String, Object> getGaugeValues();

}
```
- Add to MetricRegistry special methods to for registering, deregistering and retriving of gauge groups. The registration of simple gauges should still as is without any changes.

``` java
void registerGaugeGroup(String groupId, GaugeGroup gaugeGroup);

void removeGaugeGroup(String groupId);

SortedMap<String, GaugeGroup> getGaugeGroups();
```
- Add support of GaugeGroup for all existed reporters in the dropwizard/metrics repository. This step should be done with special caution, in order to avoid backward compatibility issues with unknown reporters outside dropwizard/metrics repository. For example due to version of java prior 1.8 is still supported and default methods can not be added to interfaces, the MetricRegistryListener interface should not be modified. But I believe it would be easy work ot implement changes.

**Next actions**
After concept will be discussed, corrected(or replaced by something better) and approved, I can do all necessary work by myself, in order to avod wasting time of dropwizards employees.

**Comment by vladimir-bukhtoyarov** [comment]
And another possible solution which does not lead to modification of MetricRegistry.

- Introducing reporting transaction/session concept(instead of GaugeGroup from first message in thread) The each  reporters should do one reporting cycle in the scope of one transaction. To achive this it is need to add only 3 lines of code to basic class ScheduledReporter

```java
public abstract class ScheduledReporter implements Closeable, Reporter { 
...
 public void report() {
        synchronized (this) {
            ReportingSessionThreadLocalStorage.beginThreadLocalSession();
            try {
                report(registry.getGauges(filter),
                    registry.getCounters(filter),
                    registry.getHistograms(filter),
                    registry.getMeters(filter),
                    registry.getTimers(filter));
            } finally {
                ReportingSessionThreadLocalStorage.closeThreadLocalSession();
            }
        }
    }
...
}
```
And class reporting session can look like this:
```
public class ReportingSessionThreadLocalStorage {

    private static ThreadLocal<ReportingSession> session = new ThreadLocal();
    
    public static void beginThreadLocalSession() {
          session.set(new ReportingSession());
    }

    public static void closeThreadLocalSession() {
          session.remove();
    }

    public static Optional<ReportingSession> getCurrentThreadLocalSession() {
         return Optional.ofNullable(session.get());
    }
}
```
public class ReportingSession {
    
   private final Map<Object, Object> attributes = new HashMap<Object, Object>();
    
   public Object getAttribute(Object key) {
         return attributes.get(key);
    }

   public void setAttribute(Object key, Object value) {
        attributes.put(key, value);
   }

}
```
So, logically coupled Gauges can share common snapshot via setAttribute/getAttribute. Multiple open session can exists in same time in case of many reporters and this is not a problem because sessions are isolated from each other via ThreadLocal.

I can implement this kind of fix in 15-30 minutes. And it looks better then solution from first post, because ReportingSession concept does not have risks to broke the backward compatibility.

**Comment by mkotelba** [comment]
Regarding grouping Metrics in general, perhaps [MetricSet](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-core/src/main/java/com/codahale/metrics/MetricSet.java) could be enhanced to (optionally) be retained + used for grouping after being passed into MetricRegistry.register instead of being immediately discarded?

Also, perhaps MetricSet could (again, optionally) provide a name prefix for those of it's Metrics that don't specify an absolute name?

**Comment by marshallpierce** [comment]
Quite understandably, you want to include your custom top-k data with the rest of the data being output by Metrics. Right now, the only tool you have to express a complex measurement is as a bunch of Gauges, but since each metric is treated independently, that arrives at the host of issues you've identified above. If we make it easier to participate in the reporting lifecycle without being forced to express anything beyond counters and histograms as Gauges (or aggregations of Gauges), then we avoid the entire problem without having to add all that complexity. 

I think this is an illustrative use case that we can use to think about how to be able to solve this sort of thing more elegantly in v4+. Perhaps the root of this pain is not so much a Gauge issue as it is that Metrics is very all-in-one in the way it handles reporting (and the scheduling of reporting). Right now, a Reporter handles its own periodic execution as well as mapping everything in the MetricRegistry to the impl-specific serialization (usually a wire format over a network socket). This means that there's no way for external code to participate in the communication with, say, Graphite (just an example; nothing here is Graphite specific). 

Consider instead a situation where scheduling, mapping of core metric types to serialized data, and a low level Graphite (or whatever) client were separated out. If scheduling and reporting and the current core types weren't so intertwined, it's not too much of a stretch to invoke the basic Metrics "write all my core metrics data to Graphite" logic and then easily follow that with your own top-k data. The whole reason that Gauges exist is a consequence of this problem: there's no tidy way to write your own data to Graphite alongside Metrics data, so you're forced to jam your data into Gauges if you want to participate. Instead of making Gauges more complicated so that it's possible to do more with them, what about making it easy to write your own data from your own measurements? Then you could do whatever analysis you want with whatever consistency model you need.

Gauges are already sort of an awkward thing as it is without worrying about transactional measurements. The only thing a Gauge gets you is that if you can constrict your data down to a Gauge<Number> or Gauge<Boolean> then it handles serialization for you because reporters usually do the serialization of that for you. As you've seen, this is very limiting. If we construct ways of grouping Gauges together, it sounds like we're just painfully re-inventing JMX CompositeData, and that wasn't exactly a great success the first time. I'd prefer to leave Gauges just as they are: a simple escape hatch for things just complex enough to not fit into a Counter or Histogram, but no more than that.

Basically, you're doing your own mapping of your complex data into Gauges and using the default serialization of Gauges. This means you don't have to worry about turning your top-k into Graphite-ese (or Prometheus or...), but instead you have a host of other problems because Gauges are assumed to be independent. If such extension points existed, would it not be preferable to skip the intermediate Gauge representation and instead do whatever histogram snapshot manipulation you pleased and write it out in sync with the rest of the metrics data? A naive implementation would mean you would need to implement different code for each storage provider (Graphite, Prometheus, Datadog, etc), but since it all ends up as (string label, numeric value) anyway I suspect that a low-level intermediate representation could address that.

**Comment by vladimir-bukhtoyarov** [comment]
Thanks a lot for explanation your plans for next major version. I glad to hear about v4.0. What is the progress of v4? Is it in the development phase? Did you published proposals to any public area? Anyway, please keep my use case in mind, you are exactly understand my needs. I think ability to expose the complex metrics via v.4,  should be the one of its readiness criterion.

I am agree with you that exposing top-k(or another complex structure) as bunch of gauges is trick, but there is no other possibility to do it in 3.x version. Reusing of exporters is not a main my goal, it is not a big deal for me to copy&past few lines of code for several reporters, or just do monkey patching of existing reporters and keep it in private repository. What I really want to avoid that is re-inventing analog of "slf4j"  for metrics. If I will need to distinguish my metrics implementations from Dropwizard metrics, then soon I will begin to build an abstraction layer - "smf4j" simple monitoring facade for java :):):) But I really do not want to do it.

I am sorry, I could be think a little bit more prior to open this issue. Today I found the solution how to solve atomicity problem without modification of basic classes. I will do it in similar way as described in second post in this topic, but point of extension will be the executor which used by ScheduledReporter. I will just wrap around the Runnable which reporter schedules to executor. The ScheduledReporter has constuctor which accepts executor as parameter. Of course, all existing reporter-builder do not accept executor as configurable parameter, but I think that it is mistake at the library level(at least for JEE environment). But this is another story is not related to current topic. I will prepare pull request for builders in few days in scope of another issue, maybe similar issue already opened, I'll try to find prior to create new.

**Comment by marshallpierce** [comment]
Alas my ability to contribute to v4 is quite time-limited; metrics competes with a lot of other things for my spare time. I've talked with Ryan a little bit about what we can do for v4 (zero-allocation reporting pipeline is high on my list of goals) but so far I haven't had the opportunity to write any substantial amount of code implementing my pipe dreams. So, don't read too much into what I personally want to see in v4, not unless metrics becomes more than a 1% time project for me... :/ I think the goals for v4 are very much up for discussion, so I hope this use case ends up being represented well.

I agree that an "slf4j for metrics" is probably not a good idea, and we should avoid creating situations that pressure people to do that. The more I think about it, the more I like the idea of having a lower-level API for writing metric data to other systems (implemented for Graphite, etc) that is used out of the box for Histogram and Counter, but could easily be used by users in your situation to report on top-k without having to cram their data into Gauges.

**Comment by vladimir-bukhtoyarov** [comment]
In conclusion: I agree that would be better to leave v.3.0 as is. So, I close this issue in hope of v.4 will solve problem descibed in this issue.

**Comment by vladimir-bukhtoyarov** [comment]
I have [started to work](https://github.com/vladimir-bukhtoyarov/metrics/commit/d9975920bae8a0fa3f706d22dcac6c5e1eac96fb) on this issue. I hope that task will be accomplished in one or two days, before "4.0" branch achieve "beta" status.
