### ISSUE TITLE
Is there any approach to reset our ''MetricRegistry''?

### ISSUE THREAD

**Issue by visionarywind** [dropwizard/metrics#1019]
It is great to hear this metrics lib, which may provide a elegant solution for my requirement of statistics for monitoring data.

I need to count performance of my program and calculate some features such as max, min, mean during a configurable period.
Here comes my question. I could not find a way to reset my metric with metrics.

Any help would be very much appreciated.

**Comment by fjamal21** [comment]
I also need this feature. Do we have any plan for this?

**Comment by saadmufti** [comment]
Instead of resetting, you could use the built in sliding time window reservoir, but keep in mind it is not memory bounded so if your event rate is high it will run into trouble, plus it is the slowest one. There is also just sliding window reservoir which represent the last 'n' events.

Also keep in mind that from the default built in exponentially decaying reservoir, you get pretty nice behavior in that it roughly represents the last five minutes, the all the quantiles it gives you plus the min and max are from a sample, so it may not be the real min or max if there are very few outliers. Good behavior of this reservoir depends on assumptions about the underlying distributions of the values. Also, it relies on getting traffic to get updated, so if there is a lull in traffic, it will happily report very old (and incorrect) values.

Hope this helps.

**Comment by marshallpierce** [comment]
I'd be interested to hear people's thoughts on some [notes on this topic I've been accumulating](https://github.com/marshallpierce/metrics-thoughts). To avoid derailing this conversation here, please file your comments as issues on that repo. Thanks, and I look forward to your feedback.
