### ISSUE TITLE
Replace as reset

### ISSUE THREAD

**Issue by randomstatistic** [dropwizard/metrics#1021]
I was reading some code, and wondering why the author was using `Map<String, Metric>` every place instead of `MetricSet`, and I finally realized it was because he couldn't use register/registerAll because he was permitting "resets" by doing replacements. Like so:

```
for (Map.Entry<String, Metric> entry : metrics.entrySet()) {
    String metricName = entry.getKey();
    Metric metric = entry.getValue();
    try {
        registry.register(metricName, metric);
    } catch (IllegalArgumentException e) {
        synchronized (registry) {
            registry.remove(metricName);
            registry.register(metricName, metric);
        }
    }
}

```

I can tell from the issue history that there's been some contention around the idea of `Metric.reset()`, but I wonder if this approach might provide a path for that. That is, by providing a set of APIs like `registry.replace` and `registry.replaceAll` that are semantically similar to `registry.register` and `registry.registerAll`, but never throw the `IllegalArgumentException`, instead binding the existing name to a new Metric instance. 

Anything that already had a reference to the old Metric would still have it, but as long as the Reporters weren't some of those things, that's pretty close to a universally applicable reset operation.

**Comment by rohansuri** [comment]
Hi @randomstatistic, I was wondering of this solution too.

If to reset the metrics upon any time a reporter reports (assume a single reporter only for now), simply remove the metric from the registry as well (that is, inside the report(..) method of a reporter).
And then anyone asking for the same metric using the name would get a new metric and hence in a way we successfully reset the metric.

But the danger is as you said:
"Anything that already had a reference to the old Metric would still have it"
which seems likely right? and hence causing the reporter to miss the updates?
since someone could be updating a metric which actually doesn't exist in the reporter now.
