### ISSUE TITLE
Add hostname to org.eclipse.jetty.util.thread.QueuedThreadPool.ThreadPool metrics

### ISSUE THREAD

**Issue by homiak** [dropwizard/metrics#1025]
When jetty is used on multiple servers that all report metrics to the same graphite server, then org.eclipse.jetty.util.thread.QueuedThreadPool.ThreadPool metrics get overriden. To avoid that it should be possible to add the hostname to the reported metrics.

**Comment by ryanrupp** [comment]
I don't use Graphite but from what I remember about it, it uses a dot delimited naming convention (instead of tags like some newer systems) so I thought usually you want to have your metrics stored in some convention like:

```
<host>.<metric_name>
```

Or could be anything really to get the uniqueness that is desired. The Graphite Reporter allows you to prefix the name that is generated in the builder [here](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java#L70). Maybe I'm understanding the problem incorrectly though because wouldn't you need this for any metric (not just the Jetty ones)? Or potentially there's times when you don't want to always prefix the host in the reported metrics? Suppose it depends how aggregations work in Graphite/what you want to achieve e.g. thread pool is definitely a metric that's unique to the application where as things like timings maybe you want to aggregate across the cluster, although I thought Graphite supported something like wildcard aggregations e.g. *.mytiming.avg

**Comment by homiak** [comment]
>>>>

I don't use Graphite but from what I remember about it, it uses a dot
delimited naming convention (instead of tags like some newer systems) so I
thought usually you want to have your metrics stored in some convention
like:

<host>.<metric_name>

>>>>>>>

Exactly! The metrics reported under
"org.eclipse.jetty.util.thread.QueuedThreadPool.ThreadPool". So when
metrics comes from different hosts to the same carbon server, it gets
overridden.

I suggest modifying this

https://github.com/dropwizard/metrics/blob/3.2-development/metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedQueuedThreadPool.java

To add the hostname

something like this:

private static String hostName;

static {
    try {
        hostName =
InetAddress.getLocalHost().getCanonicalHostName().replaceAll("[^a-zA-Z0-9-]",
"-");
    } catch (UnknownHostException e) {
        LOG.error("can not get local host name ", e);
    } finally {
        if (hostName == null) {
            hostName = "localhost";
        }
    }
}



@Override
protected void doStart() throws Exception {
    super.doStart();
    metricRegistry.register(name(TimingReports.getHostName(),
QueuedThreadPool.class.getCanonicalName(), getName(), "utilization"),
new RatioGauge() {
        @Override
        protected Ratio getRatio() {
            return Ratio.of(getThreads() - getIdleThreads(), getThreads());
        }
    });
    metricRegistry.register(name(TimingReports.getHostName(),
QueuedThreadPool.class.getCanonicalName(), getName(),
"utilization-max"), new RatioGauge() {
        @Override
        protected Ratio getRatio() {
            return Ratio.of(getThreads() - getIdleThreads(), getMaxThreads());
        }
    });
    metricRegistry.register(name(TimingReports.getHostName(),
QueuedThreadPool.class.getCanonicalName(), getName(), "size"), new
Gauge<Integer>() {
        @Override
        public Integer getValue() {
            return getThreads();
        }
    });
    metricRegistry.register(name(TimingReports.getHostName(),
QueuedThreadPool.class.getCanonicalName(), getName(), "jobs"), new
Gauge<Integer>() {
        @Override
        public Integer getValue() {
            // This assumes the QueuedThreadPool is using a
BlockingArrayQueue or
            // ArrayBlockingQueue for its queue, and is therefore a
constant-time operation.
            return getQueue().size();
        }
    });
}


I hope that make it clear.

You are right that it is possible to define a different graphite prefix for
each host, but I think that is not what it should be used for. I think
graphite prefix should be application based, not the host based. Since we
are running the same app on multiple hosts that would not be a preferred
solution.

Thanks for your help.

Regards
Peter

**Comment by ryanrupp** [comment]
It looks like the Jetty metrics support a prefix in the constructor [here](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHandler.java#L90)  - so you could use that to prefix with the hostname. I don't think everyone will want that behavior so instead can use the 

As for prefixing all the metrics being reported from Dropwizard metrics to graphite I suppose this depends on your use case but in tagged based systems this is nice so you can answer aggregate questions like "what is the average time for this request across all nodes in the cluster" (single timeseries line graph) but also at the node level "what is the average time by node" (produces a time series line per node). With Graphite it looks like you can do this with wildcard queries although I can't speak to its performance/if it's a best practice.

**Comment by arteam** [comment]
I think it should be closed via #947
