### ISSUE TITLE
What's the difference between gauges and counters?

### ISSUE THREAD

**Issue by mayooran99** [dropwizard/metrics#1043]
Usually counters are used for values that always increment where as gauges are used for values that increment and decrement, such as temperature. But Java Metrics provides a decrement function on Counters. So what is the difference between gauges and counters in this case?

**Comment by vladimir-bukhtoyarov** [comment]
I, too, was very surprised when I saw the method to decrement for counter.

**Comment by PatrickOsborne** [comment]
Let's say that a system uses a Java queue which already has a size method.
An implementer has two paths to expose the queue size as a metric:
1) wrap the queue and have the wrapper update a counter when objects are
queued or deqeued, or
2) implement a gauge that calls the size method of the queue periodically.

The second approach is vastly simpler to implement.

So in my mind, use a counter where possible in an application and use a
gauge when necessary to integrate with some existing construct in an
application.

-- Patrick

On Jan 15, 2017 7:27 AM, "Vladimir Bukhtoyarov" <notifications@github.com>
wrote:

I, too, was very surprised when I saw the method to decrement for counter.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dropwizard/metrics/issues/1043#issuecomment-272698503>,
or mute the thread

**Comment by mayooran99** [comment]
@PatrickOsborne Why would we have to wrap the queue? we can still have a counter inside the queue and let it inc and dec? Why is a wrapper needed for the queue?

**Comment by PatrickOsborne** [comment]
How would you add a counter to a class that is part of the JDK?  I would do
it by extending the queue or creating a new object which wraps the queue
and presents its own API.  I'd like to hear how you would approach that
problem

**Comment by mayooran99** [comment]
Oh you mean add a counter to the queue itself. Apologies. I was thinking of having a counter in the class where the values are being added to the queue and retrieved to process. Your explanation makes sense.

**Comment by pilhuhn** [comment]
A decreasing counter could be used when you start with e.g. 1000 credits and decrease by 1 for each call to a certain api.
