### ISSUE TITLE
How to reset counter once reported to statsd

### ISSUE THREAD

**Issue by myanything** [dropwizard/metrics#1045]
I think this is a already-asked question. But I did not find an answer yet.

So basically, I have a set of servers, and each server will report  counters, say service request count and I have a reporter that reports to statsd (which underlying relay to graphite). So as we know, the counter in Metrics library keeps increasing. But this will mess up the statsd/graphite system, as they have their aggregation algorithm, e.g. bucking the stats data and applying different agg functions. But without reseting the counter after reporting, the graph generated by graphite will be totally wrong. Curious how is this fixed?

Thank you!

**Comment by vladimir-bukhtoyarov** [comment]
Which reporter You use to export metrics to StatsD? If it is source open, I can look to it and point to problem. IMHO, proper handling of counters should be done on reporter side. Of course you can use [ResetOnSnapshotCounter](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/src/main/java/com/github/rollingmetrics/counter/ResetOnSnapshotCounter.java) from rolling-metrics, but I argue that fix on reporter side will be proper solution, just remember previous observed value from counter and report delate from current value of counter.

**Comment by myanything** [comment]
@vladimir-bukhtoyarov thank you for replying. The lib I used is the [ReadyTalk](https://github.com/ReadyTalk/metrics-statsd) one, which just directly emit what the counter value is.

**Comment by vladimir-bukhtoyarov** [comment]
As I found from source code [ReadyTalk/metrics-statsd](https://github.com/ReadyTalk/metrics-statsd/blob/master/metrics-statsd-common/src/main/java/com/readytalk/metrics/StatsD.java#L96) [gauge], ReadyTalk/metrics-statsd send everything as [gauge](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges). The Gauge type in StatsD type-system means that nothing will be aggregated, in other words StatsD will just exactly resent to Graphite the data what provided without doing any useful work. So, first of all, I want to ask question, why you are not using [Graphite Reporter](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java) built-in to Dropwizzard/Metrics?

Secondly, looks like your problem can be solved at presentation layer without modification of anything in your pipeline. You just need to configure presentation tool (which you use to visualization of graphs) to draw  delta between values instead of presentation values as is. For example, in my company we are using Zabbix instead of Graphite and we report Counter as is, but graphs tuned to present values as deltas.

**Comment by vladimir-bukhtoyarov** [comment]
1. Metrics core is general solution which is used including high-load applications. For example in my case, there are several applications which perform updating of metrics about 10000 times per second. Storing original timestamp is possible only for little loaded applications, because it require to store each source event independently from each other, and this leads to risk of OutOfMemoryError. To avoid OutOfMemoryError implementation need to store events outside its memory on the disk or network storage and this is risk to overload application(or network at whole) by IO. Please read [metrics-thoughts
](https://github.com/marshallpierce/metrics-thoughts#motivating-example-service-processing-time) to get deeper understanding.
So, as mentioned MetricsCore as general solution can not store timestamp of each event, it just sends single timestamp for batch of metrics. If You still need in this functionality then just implement own Timer, I hope you will understand all risk at moment of implementation.

2. I am not so familar with Graphite(because I use Zabbix). But I believe that modern monitoring database must provide solution to aggregate counters. Read aggregation rules for [Carbon](http://graphite.readthedocs.io/en/latest/config-carbon.html#aggregation-rules-conf). I did quick reading of this [stackoverflow topic](http://stackoverflow.com/questions/13697553/why-use-statsd-when-graphites-carbon-aggregator-can-do-the-same-job) and I am sure that Carbon already provide functionality for counter aggregation.

**Comment by myanything** [comment]
@vladimir-bukhtoyarov thank you for share the  [metrics-thoughts](https://github.com/marshallpierce/metrics-thoughts#motivating-example-service-processing-time) link, that is pretty helpful.
