### ISSUE TITLE
Feature request: Record and query the past n-minutes rate of an event.

### ISSUE THREAD

**Issue by behrangsa** [dropwizard/metrics#1125]
My app has an operating that should happen at least once (possibly thousands of times) per minute.

I can't use `com.codahale.metrics.Meter#getOneMinuteRate` as it still takes into account older occurrences, albeit with a lower weight.

This FR is to add a mechanism to record and query the past n-minute rate of an event, ignoring all the events before that.

**Comment by storozhukBM** [comment]
Hi @behrangsa,
I think you can use `com.codahale.metrics.SlidingTimeWindowReservoir` for such purposes.
But in this case should manually create `Timer` and/or `Histogram` with specified reservoir and then register it.

**Comment by vladimir-bukhtoyarov** [comment]
@storozhukBM reporting of rates, does not depend from type of reservoir, timer configured with SlidingTimeWindowReservoir will report absolutely same rates as timer configured with ExponentiallyDecayingReservoir.

**Comment by vladimir-bukhtoyarov** [comment]
@behrangsa  Why do you interest only for rates and do not interest for latency distribution(histogram) of last n-minute events? I ask, because I am creator of [rolling-metrics](https://github.com/vladimir-bukhtoyarov/rolling-metrics) extension for Dropwizzards/Metrics, and request for rates without percentiles looks very strange for me, could you describe your use case s little bit?

**Comment by behrangsa** [comment]
@vladimir-bukhtoyarov I think my requirements got lost in translation. 

What I need is to ensure that a given activity has occurred at least once in the past `n`-minutes, like a heartbeat. 

Anything beyond that (e.g. how many times did the even occur in the past event) is nice to have but not a requirement for my particular case.
