### ISSUE TITLE
Slight refactoring request to allow DropWizard Metrics integration with MicroProfile

### ISSUE THREAD

**Issue by kwsutter** [dropwizard/metrics#1161]
(I'll start with the details since coders like to know the details...  Then, I'll introduce our efforts.)

We're evaluating the core parts of Dropwizard metrics for our new Eclipse MicroProfile metrics spec.  In order to fit well in a spec, it's important that the API and implementation are separated (so that the API can be easily exposed without intermixed implementation details, and so the jars can be signed).  To that end, our investigation seems to show that there are 9 files in the com.codahale.metrics package that are actually implementation files.  We would like to request that you relocate the following files to an implementation package (eg. com.codahale.metrics.impl):

```
/metrics-core/src/main/java/com/codahale/metrics
        ChunkedAssociativeLogArray.java
        LongAdder.java
        LongAdderAdapter.java
        LongAdderProxy.java
        MetricAttribute.java
        SlidingTimeWindowArrayReservoir.java
        Striped64.java
        ThreadLocalRandom.java
        ThreadLocalRandomProxy.java
```
(Now the introduction...)

Not sure if this is your first exposure to MicroProfile or not, but we're trying to fill the gaps in the Enterprise Java space related to microservices programming model and development.  [Check us out!](http://microprofile.io/)  We'd love to include your team in our efforts.  There are several [components](https://github.com/eclipse?utf8=%E2%9C%93&q=microprofile&type=&language=) that make up the Eclipse MicroProfile project.  The Metrics effort is still early in it's development stages, but we do have [this Metrics Proposal ](https://github.com/eclipse/microprofile-evolution-process/blob/master/proposals/0002-metrics.md) approved for further development.

Most of our discussions are handled via [Google Groups](https://groups.google.com/forum/#!forum/microprofile), but we also use a weekly hangout to discuss items of interest "in person".  Here's a [calendar of our MicroProfile events](https://calendar.google.com/calendar/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&ctz=GMT&pli=1). 

Sorry for the long introduction, but I didn't have a specific contact name for your team.  If you have an interest in joining the MicroProfile community or just discussing possibilities, please feel free to reach out to either [myself, Kevin Sutter](mailto:kwsutter@gmail.com) (MicroProfile co-project lead) or [Heiko Rupp](mailto:hrupp@redhat.com) (lead for the MP Metrics effort).

**Comment by ryantenney** [comment]
Hi Kevin,

Thanks for reaching out!  We can certainly discuss this as part of Metrics 4.  Let me read the documents you've linked and get back to you within a couple days!

Ryan

**Comment by kwsutter** [comment]
Sounds good, Ryan!  Thanks.  FYI, I am out starting Friday for a week.  If
I don't respond in a timely fashion, please reach out to either Heiko Rupp
or Don Bourne.

**Comment by arteam** [comment]
I've been working recently on Metrics 4, you can see the current state in the [4.0-development](https://github.com/dropwizard/metrics/tree/4.0-development) branch. It targets Java 8, removes JMX from the core, cleaned up internally, but mostly maintain the same public API as 3.2.

* The 4.0 version will not have classes:
```
LongAdder.java
LongAdderAdapter.java
LongAdderProxy.java
Striped64.java
ThreadLocalRandom.java
ThreadLocalRandomProxy.java
```
because we will use directly API provided by `java.util.concurrent`. 

* I believe the `MetricAttribute` class is part of the public API, because it's used in the configuration of reporters to filter out attributes.

* `SlidingTimeWindowArrayReservoir.java` could be hidden, but then it makes sense to hide all `Reservoir` implementations which are currently 5.

I think we could extract required public classes from `metrics-core` to a `metrics-api` module to provide a minimal common API other metrics providers. I think the main requirement for us is to maintain the `com.codahale.metrics` namespace, because [many](http://metrics.dropwizard.io/3.2.3/manual/third-party.html) 3rd party metrics instrumentation and reporting libraries depend on it.

**Comment by pilhuhn** [comment]
+1 on hiding the `Reservoir` implementations

**Comment by donbourne** [comment]
Following up on what Kevin said when he started this thread, we've recently put out the first release of MicroProfile Metrics at  https://github.com/eclipse/microprofile-metrics/releases/tag/1.0 .  

We started from the Dropwizard Metrics com.codahale.metrics and com.codahale.metrics.annotation packages.  DWM was a great base API for us to work from as it contained all the key metric types and concepts necessary to get people able to be productive quickly.  

We very much appreciate the thought and work that has gone into DWM and look forward to discussing with you further on how we might collaborate in the future.
