### ISSUE TITLE
What units are metrics in when using methods like  timer.getOneMinuteRate()

### ISSUE THREAD

**Issue by aljohnso** [dropwizard/metrics#1171]
what unit is returned

**Comment by ryanrupp** [comment]
See documentation [here](http://metrics.dropwizard.io/3.2.3/getting-started.html#timers) - by default rates are in seconds and durations are in nanoseconds. However, most of the reporters (the scheduled ones at least) allow you to convert these to whatever you want for reporting purposes e.g. maybe you want milliseconds for durations and minutes for rates. For instance see the graphite reporter configuration [here](https://github.com/dropwizard/metrics/blob/4.0-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java#L118) which then leverages the base class ScheduledReporter that provides the logic for converting the values [here](https://github.com/dropwizard/metrics/blob/4.0-development/metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java#L139).

Side note but looking at the code I realized if for some reason you wanted to report rates in milliseconds this wouldn't work correctly (doubt anyone does this but for the conversion code to work the base unit needs to be the lowest possible unit, generally works because nanoseconds for duration is the lowest and for rate it would probably never make sense to report at a unit smaller than seconds).

**Comment by aljohnso** [comment]
thanks so much was going crazy looking for this
