### ISSUE TITLE
Drop-wizard metrics 3.2.3 jars support for IBM JDK 1.6

### ISSUE THREAD

**Issue by Bhavanish1** [dropwizard/metrics#1215]
Team,
 
We need drop-wizard metrics 3.2.3 jars support for IBM JDK 1.6
 
Metrics-servlets-3.2.3 is having one transitive dependency profiler-1.0.2
 We also do not see any mention of support for JDK 1.6. Can we get the built in version for IBM JDK 1.6
 
Caused by: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: JVMCFRE003 bad major version; class=com/papertrail/profiler/jaxrs/CpuProfileResource, offset=6
 at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:176)
 at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:749)
 ... 20 more
 Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/papertrail/profiler/jaxrs/CpuProfileResource, offset=6
 at java.lang.ClassLoader.defineClassImpl(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:273)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74)

We had raised a ticket https://secureweb.jpmchase.net/https://github.com/dropwizard/dropwizard/issues/2183
We were told to reach out to metrics team

Appreciate your help

Thanks
Bhavanish

**Comment by arteam** [comment]
I guess you can't use the `AdminServlet` with papertrail which is compiled against Java 7. I think the best option for you would be to copy `AdminServlet` from `dropwizard-servelts` and manually remove the `CpuProfileServlet` dependency.

**Comment by Bhavanish1** [comment]
We are trying to migrate from codahale to dropwizard metrics. We tried with the latest dropwizard jar. 
However its not compatible with IBM JDK 1.6. 
This is one of the issues seen and we could face more with other scenarios
Will you be able to provide us the dropwizard metrics jars which are compatible with IBM JDK 1.6.

**Comment by arteam** [comment]
Dropwizard 3.2 should be compatibe with JDK 1.6. Only `AdminServlet` from `dropwizard-servlets` is depended on a JDK 1.6 dependency. If you use only `metrics-core`, you should be fine.

**Comment by Bhavanish1** [comment]
We are using metrics-core, metrics-json, metrics-jvm, metrics-servlets. 
Are you saying we can use all above with JDK1.6  for Dropwizard 3.2?
Can't we use Dropwizard 3.2.3?
This is the main reason for upgrade: Dropwizard has a jvm monitoring component that looks at GC and we want to utilise it for monitoring

**Comment by arteam** [comment]
You don't need `metrics-servlets` and `metrics-json` if you don't expose your metrics via an HTTP API.
You can't use `AdminServlet` from  `metrics-servlets` from your app, because it has a Java 1.7 dependency.  If you really need it, I advice to downgrade to the 3.1.5 version which doesn't have a `cpu-profile` dependency.

**Comment by ngreddyravi** [comment]
Metrics-servlets-3.2.3 is having one transitive dependency for profiler-1.0.2 which is causing the issue related to JDK1.6 compatibility. Above trace provided is related to this.
Even if we exclude this jar, we are not sure what other underlying dependencies may discover at a later point. 
We are not using AdminServlet. However, we are using MetricsServlet due to which we cannot ignore the metrics-servlet dependency.

We don't see any details around these jars compatibility with JDK1.6 as part of release notes. Is this made available as part of any documentation on what supports JDK1.6 and what not?

**Comment by arteam** [comment]
`metrics-core` should be compatible with Java 6 and doesn't have any dependencies. In 3.2.0 a transitive Java 7 dependency to `cpu-profiler` was added to `metrics-servlets`, which makes `AdminServlet` incompatible with Java 6. To solve this you can pull an earlier version of `AdminServlet` (e.g. 3.1.5) and exclude `metrics-code` dependency from it.
