### ISSUE TITLE
Consider WeakReference to Metrics in MetricsRegistry

### ISSUE THREAD

**Issue by bentatham** [dropwizard/metrics#1267]
On multiple occasions (admittedly, due our own bugs), we have added metrics to the registry to gather metrics on a time-limited system, and then failed to remove those metrics from the registry at the end.  Over a long lived application, this has led to memory leaks that eventually lead to OutOfMemory errors.

We were trying to think of a way to remind of us of this problem (like `AutoCloseble` resources that IDE/static analysis can warn  you about, but in most cases, the registration of the metric is in a different scope than where we would remove that metric.

Currently, metrics are stored in a `ConcurrentMap` in `MetricsRegistry` (specifically, `ConcurrentHashMap`, by default)

As a precaution to avoid memory leaks, I wonder if the metrics library should consider storing the metric objects themselves as a weak or soft reference so that if the object that was updating the metric disappears, the metric will eventually be cleaned up.  You could consider using one of the options in guava's MapMaker, for example, to do this quite easily and little change to the actual metrics library code.

Or perhaps we could just do this ourselves by override `MetricRegistry.buildMap`.

**Comment by bentatham** [comment]
Also, calling an non-final method (like `buildMap`) from the constructor is a generally frowned upon practice - jcip, effective java, and many other sources talk about it.  It would be better to pass in a `Supplier<Map<String, Metric>>` to the constructor.

**Comment by tguzik** [comment]
I'm not sold on the weak reference idea honestly. While i don't use them myself, some workflows may be generating the metric names at runtime without storing a hard reference (think generic endpoint metrics for a Jersey/JAX-RS interface), which may lose the data the user cares about when/if garbage collector decides to remove the metric.

Perhaps it would be better to let the user control this process - let them mark that a certain metric is allowed to be auto-removed if not used for a set period of time? Using your example it would be like using Guava's `CacheBuilder#expireAfterAccess(long,TimeUnit)` instead of a `WeakReference`

**Comment by arteam** [comment]
I concur. I think providing an API for the specifying the storage format would be the best option. We could extract creating a map to a specific method like `Map<MetricName, Metric>` newMap()`. Users can use `LinkedHashMap` to simulate a bounded cache or use [expiringmap](https://github.com/jhalterman/expiringmap) for a time-based expiration cache.
