### ISSUE TITLE
Metric tags and Prometheus

### ISSUE THREAD

**Issue by davbo** [dropwizard/metrics#1272]
Hi, we're currently working on moving our operational metrics over from being Graphite-based to being Prometheus-based. We looked into the support for Prometheus in Dropwizard and are really pleased to see the recent changes to introduce tags with the MetricName.

We made some experimental changes to the Prometheus [simpleclient_dropwizard](https://github.com/prometheus/client_java/tree/master/simpleclient_dropwizard) and thought it could be useful to highlight some observations here while tag support is still in development.

## Specifying tag values when creating a MetricName ##

In the example of [interface.traffic from the PR](https://github.com/dropwizard/metrics/pull/1250) introducing tags 2 MetricName's need to be created, one with the tags setting "direction"="in" and one setting "direction"="out". Direction has a cardinality of 2.

Here's an example of Prometheus metrics we collect:

```
http_requests_total{method="get",host="example.com",path="/",code="200"} 2
http_requests_total{method="get",host="example.com",path="/foo",code="200"} 10
```

In the Dropwizard model we would need an instance of the MetricName for:

  `number of methods * number of paths * number of status codes`
  
Each of these MetricName instances would be associated with a different Counter.

In comparison the Prometheus implementation places the abstraction within the Counter (or whichever metric type) itself. So a single `http_requests_total` counter contains a `Map<List<String>, Counter>` ([actual implementation](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java#L54)) Increments are done by calling `httpRequestsCounter.labels("get", "/foo", "200").inc()`. This way users only have to manage the one httpRequestsCounter object.

Are the changes to add tag support intending to handle the case of labels or combinations of labels which may have higher cardinality? e.g. paths / status_codes.

Would a pull request changing the implementation to be closer to that of the Prometheus Java client be welcomed? (I'm not saying we'd be able to produce that, just interested in how settled you are on the current implementation)

**Comment by arteam** [comment]
Thank you for your interest in Metrics 5.0! The proposed changes sound reasonable and I would gladly review a PR for handling of labels with higher cardinality. I'm not settled on the Metrics tags implementation and I'm completely fine with changes driven by implementations of reporters to tag-based timeseries databases like InfluxDb, Prometheus, and OpenTSDB. The goal of Metrics 5.0 is too close the gap between Java abstraction and such databases.

**Comment by davbo** [comment]
I've made a proof-of-concept here: https://github.com/dropwizard/metrics/compare/5.0-development...davbo:follow-prometheus-pattern-for-tags

The changes are mostly lifted from https://github.com/prometheus/client_java but include adding a requests-counter metric to the InstrumentedHandler for Jetty, hopefully this gives is a good idea of how the interface might look if taken any further. 

No idea how this fits with the MetricRegistry or MetricSet's in metrics-core. Interested to hear your thoughts on what would be needed to progress beyond a proof-of-concept.

**Comment by smojtabai** [comment]
Just chiming in here that I think your interface makes sense and reducing the number of objects to manage is nice +1.

**Comment by mbrannstrom** [comment]
Here is another take on the prometheus style tags, see poc here: https://github.com/dropwizard/metrics/compare/5.0-development...mbrannstrom:5.0-prometheus-tags

This one avoids the inheritance of all metrics classes from `TaggedMetric`. Instead the builder class called `NamedMetric` achieves pretty much the same thing. See the `NamedMetricTest` for intended usage. Also, I think having key-value-pairs in the `tag` method is more readable e.g. `tag("method", "get", "path", "/foo")` or `tag("method", "get").tag("path", "/foo")` rather than just `tag("get", "/foo")`.

If MetricName (and thus NamedMetric) methods `resolve` and `tagged` were renamed to `name` and `tag` respectively, the usage would perhaps be even nicer.

The method `counter2` should have a better name... perhaps the original `counter` (et al) methods should be replaced altogether? I.e. old `counter("foo")` becomes `counter("foo").get()`
