### ISSUE TITLE
metrics-ganglia 4.0.2 not available in Maven repos

### ISSUE THREAD

**Issue by sigram** [dropwizard/metrics#1319]
The latest version available at Maven Central is 3.2.6. Has this artifact been removed or rolled into another one?

**Comment by arteam** [comment]
Yes, metrics-ganglia was removed in Metrics 4.0.*. We don't support it anymore.

**Comment by arteam** [comment]
https://github.com/dropwizard/metrics/commit/56791042fa2ab6fc93aa0038fc4bdfd955a34cfe

**Comment by sigram** [comment]
What was the reason for this change? The commit above doesn't mention anything specific.

**Comment by arteam** [comment]
If my memory servers me right, there were licensing issues with the Ganglia client library which was released under LGPL.

**Comment by henrik242** [comment]
@arteam: The removal isn't mentioned in the 4.x release notes: https://metrics.dropwizard.io/4.0.0/about/release-notes.html

Also ganglia is in https://metrics.dropwizard.io/4.0.5/manual/ganglia.html  (but that `4.0.5` URL seems wrong somehow, since https://metrics.dropwizard.io/4.0.5/about/release-notes.html only mention 3.x and older)
