### ISSUE TITLE
Basic - Histogram output in JmxReporter

### ISSUE THREAD

**Issue by abennet** [dropwizard/metrics#1340]
I have a very basic question trying to  use a codehale histogram (metrics-core 4.0.3). My application is updating the histogram value and I can see via Jconsole that the count is being updated as well. 
The problem is that all of the percentiles show 0, as well as the min and the max. However, when I access the histogram.getSnapshot() through the debugger, its max value is non-zero. 

What is the disconnect here? How should I be viewing the state of a histogram metric?

Thank you!

**Comment by dingwa** [comment]
Hi,

I have just run across this issue and I have found that the JmxReporter calls metric.getSnapshot() for each exposed JMX method.  However if you're using a Histogram Reservoir that resets upon calling snapshot, which is necessary if you want to track percentile latencies through time.  Then there is an issue since each call to getSnapshot() resets the underlying histogram.

Is this something that you've come across before and an particular ideas on how to have this resolved?

Thanks in advance!
