### ISSUE TITLE
JMX reset operation on metrics

### ISSUE THREAD

**Issue by kgs** [dropwizard/metrics#143]
It would be really great to have operation "reset" on every metric exposed via JMX.

**Comment by roytruelove** [comment]
+1 on this.  Very sad but I can't use this library without the ability to reset.

**Comment by wrprice** [comment]
+1

**Comment by amanhigh** [comment]
After reading all responses i see only way to reset is using some or other hack. A Simple Counter which resets after reporting data or fixed time interval becomes difficult to realize.

One way is described here.
http://evertrue.github.io/blog/2013/10/14/resettable-counters-with-codahale-metrics/

**Comment by jmason** [comment]
There's another workaround, BTW.

If the desire is to zero Histograms and Timers after each report, this can be accomplished by using the HdrHistogramResetOnSnapshotReservoir from https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir/ ; this is pretty clean.

Alternatively, if you want to reset counters, another way is to subclass the desired Reporter class, use that subclass in your own app, and add an override processCounter() method which uses:

```
        long count = counter.getCount();
        // report the value in the usual way
        counter.dec(count);  // reset the counter for the next iteration
```

(pretty similar to @amanhigh 's suggestion, but without the creation of a Gauge.)

**Comment by jan-molak** [comment]
@jmason - thanks for your suggestion, Justin. We're facing the same difficulty with gauges and counters being reported to the db even though their state hasn't been updated (ie. the client reporting them is down).

I can't see the `processCounter()` you're referring to in the `3.1.0` code base, could you please point me to the right place?
There is for example the `ScheduledReporter::report` method, but then resetting the state of stats at that stage would mess up any other reporters listening on the same `MetricRegistry`...

It's possible to add a `ResettingReporter` that would affect the state of the `MetricRegistry` when it's called, but this would result in similar synchronisation issues as described above. 
It looks like every reporter is running on a separate thread, and with a separate polling schedule - which gives @codahale more flexibility (you can have as many reporters as you want and don't need to care about their schedule), but takes away the control over the process.

I think the reason why Etsy's statsd supports resetting metrics upon a flush is that because [the way they've implemented it](https://github.com/etsy/statsd/blob/master/stats.js#L91) it's the "`MetricRegistry`"that's in control, rather than the reporters. Their equivalent of `MetricRegistry` sends a `flush` event to all its listeners, and then resets the metrics.
This way you don't have the flexibility of running reporters with different polling intervals*, but you can make sure that if the metric hasn't been updated within a given interval - it wouldn't be (incorrectly) reported to whatever db you're using.

Thinking about it, it seems like it might make sense for something to look after the state of the `MetricRegistry` and periodically clean up the state of metrics that haven't been updated recently?** Although this would probably result in synchronisation issues anyway.

Alternatively, each `Reporter` could receive a *snapshot* of state of the `MetricRegistry` with metrics cleaned up according to it's own flush interval. This way in the `ScheduledReporter` rather than [getting the data directly](https://github.com/dropwizard/metrics/blob/efa52f349d058e660a24097676fc27783ac1d083/metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java#L158) from the `MetricRegistry`:
```java
    public void report() {
        synchronized (this) {
            report(registry.getGauges(filter),
                    registry.getCounters(filter),
                    registry.getHistograms(filter),
                    registry.getMeters(filter),
                    registry.getTimers(filter));
        }
    }
```

we could obtain a snapshot from *somewhere* first:

```java
    public void report() {
        synchronized (this) {
            MetricRegistry snapshot = registry.getSnapshotFor(period); 
                  // the snapshot would filter out any stats 
                  // that haven't been updated within the specified period
                  // This could also be configurable per reporter; as a template method for instance
            report(snapshot.getGauges(filter),
                    snapshot.getCounters(filter),
                    snapshot.getHistograms(filter),
                    snapshot.getMeters(filter),
                    snapshot.getTimers(filter));
        }
    }
```

Thoughts? Would that be a sensible approach? Would you consider such pull request, @codahale, @ryantenney 

---
(*) well, you could have, but it would be tricky to implement

(**) recently as in: take the lowest common denominator of all the reporters' intervals and delete all the metrics that haven't been updated within that period?

**Comment by jmason** [comment]
'There is for example the ScheduledReporter::report method, but then resetting the state of stats at that stage would mess up any other reporters listening on the same MetricRegistry...'

Yeah -- that's a limitation we've chosen to accept in order to be able to do this (we're using a StatsdReporter which delivers to statsd, which requires deltas rather than absolute values).  It would be nice to come up with an approach that didn't bring that limitation.

**Comment by DanielYWoo** [comment]
+1

**Comment by wyzssw** [comment]
I WANT RESET +1

**Comment by wyzssw** [comment]
TO COUNT DAU

**Comment by nailding1** [comment]
I ALSO WANT RESET ！！！
