### ISSUE TITLE
Counter doesn't work well with Graphite multiple retentions

### ISSUE THREAD

**Issue by leonfancy** [dropwizard/metrics#1445]
Dropwizard `Counter` is keeping increasing since startup, and won't reset after report to Graphite. This caused tricky problems. 

I have setup Graphite with below configurations:

_storage-schemas.conf_
```
[default_1min_for_1day]
pattern = .*
retentions = 10s:15m,1m:6d
```
_storage-aggregation.conf_
```
[count]
pattern = \.count$
xFilesFactor = 0
aggregationMethod = sum
```
This means Graphite save a datapoint for every 10 seconds within latest 15 minutes. After 15 minutes, Graphite aggregate the datapoints of every 1 minutes to one datapoint. 
For metrics with name endint with `.count`,  the `aggregationMethod` is `sum`, so every 6 datapoints will be added up to generate 1 datapoint after 15minutes.  
For more explanation, please refer to [Graphite documentation](https://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf).

For testing, I set up a counter with name `localhost.ropc.http.request.ropcGrant.token.count`, my application inrements this counter by 1 every 10 seconds. The application also report this counter to Graphite every 10 seconds.

After 2 minutes, I request graphite and get the datapoints as below (left value is the counter value, and right is timestamp).
```
# target = localhost.ropc.http.request.ropcGrant.token.count
[0,  1560159600]
[1,  1560159610]
[2,  1560159620]
[3,  1560159630]
[4,  1560159640]
[5,  1560159650]
[6,  1560159660]
[7,  1560159670]
[8,  1560159680]
[9,  1560159690]
[10, 1560159700]
[11, 1560159710]
[12, 1560159720]
[12, 1560159730]
[12, 1560159740]
[12, 1560159750]
[12, 1560159760]
[12, 1560159770]
``` 
When I draw these datapoints in Grafana, I use `nonNegativeDerivative()` function to get the delta value.
```
# target = nonNegativeDerivative(localhost.ropc.http.request.ropcGrant.token.count)
[0,  1560159600]
[1,  1560159610]
[1,  1560159620]
[1,  1560159630]
[1,  1560159640]
[1,  1560159650]
[1,  1560159660]
[1,  1560159670]
[1,  1560159680]
[1,  1560159690]
[1,  1560159700]
[1,  1560159710]
[1,  1560159720]
[0,  1560159730]
[0,  1560159740]
[0,  1560159750]
[0,  1560159760]
[0,  1560159770]
```
This gives me how many events happened at each 10 seconds.

However after 15 minutes, when I query the datapoints during this time span, I get: 
```
# target = localhost.ropc.http.request.ropcGrant.token.count
[15, 1560159600]
[51, 1560159660]
[72, 1560159720]
```
Based on the aggregation rule, each datapoint is the sum of 6 datapoints within corresponding minute. If I still use `nonNegativeDerivative()` to get how many events happened in each 1 minutes, I will get:
```
# target = nonNegativeDerivative(localhost.ropc.http.request.ropcGrant.token.count)
[15, 1560159600]
[36, 1560159660]
[21, 1560159720]
```
This is wrong! The expected result is:
```
# target = nonNegativeDerivative(localhost.ropc.http.request.ropcGrant.token.count)
[5, 1560159600]
[6, 1560159660]
[1, 1560159720]
```

This problem is caused by the aggregation method of Graphite, however I can't change it as Graphite configuration is controlled by other team in my company. 

If Drapwizard counter could report delta value to Graphite, this problem can be resolved.

**Comment by tguzik** [comment]
I'm afraid the counter is not the abstraction you want for this - as [per documentation](https://metrics.dropwizard.io/4.0.0/manual/core.html#counters) counters are simple incrementing/decrementing 64-bit integers, with no state tracking.

As an alternate i'd suggest considering one of the following methods to get the same end result:

* Create a custom metric under existing name that would automatically reset the value to zero if last data point is not within current second (could be just two values under the hood - a counter and a numeric timestamp of last update).  
* If you know that it is Graphite taking a measurement, you could use a Gauge that returns a delta since last call (or since the last time the housekeeping thread updated the value - either way it's similar to the previous point).
* If you know that it is Graphite taking a measurement, you could reset the counter to zero afterwards.
* Depending on what is this value and what it is really used for later on, you could consider using a Meter or a Timer

The first point is probably the most robust long term, imo. I'd still keep the old counter under a different name, though.

**Comment by leonfancy** [comment]
I'm using the `@Timed` annotation on my Spring Boot controller method. 
```
@RestController
public class ExampleController {
    @GetMapping(value = "/ropc-grant/token")
    @Timed("http.request.ropcGrant.token")
    public ResponseEntity grant() {
       ....
    }
}
```

This Timer has a counter whith name `http.request.ropcGrant.token.count` that I mentioned above. Do you mean this counter is not good in this case?

**Comment by leonfancy** [comment]
If not using counter, how can I monitor the "request count during each report interval"?
