### ISSUE TITLE
Large number of WeightedSnapshot$WeightedSample instances in heap

### ISSUE THREAD

**Issue by metame** [dropwizard/metrics#1516]
During a heap dump analysis for a long running process, I noticed the `com.codahale.metrics.WeightedSnapshot$WeightedSample` class being in the top 10 of my histogram for number of items (currently 1,959,523). A heap analysis tool determined that 1,943,542 of these instances are garbage. While this doesn't take up a large amount of memory, it appears that they aren't getting gc'd. 

 I am wondering under what circumstances might this occur and if upgrading from our current use of 3.2.2 would help this issue at all?

**Comment by vladimir-bukhtoyarov** [comment]
@metame 

As you can see [from source code](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java#L29), the default Reservoir implementation produces the garbage on each update of the histogram. This garbage is very awkward for everyone GC, because all modern GC implemented across *Soft Generational Hypothesis*:
* Most of the objects become unused quickly.
* The ones that do not usually survive for a (very) long time.

```WeightedSample``` does not become unused quickly, because the moment of time when it becomes unreachable very depends on the histogram update rate. Because the update rate usually is not huge, the time that ```WeightedSample``` stays reachable is enough to promote it to the Old regions.
At the same time, the fact that ```WeightedSample``` survived does not mean that  ```WeightedSample``` should survive for a long time, because it survived just by mistake.

So default implementation of Reservior totally contradicts underlying JVM implementation, and to solve the problems with middle age garbage you need to switch to another one which never allocates something on each update. For example:
* [SlidingTimeWindowArrayReservoir](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowArrayReservoir.java) which built into Metrics core library
* [RollingHdrHistogramBuilder](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/histograms.md) from third-party library (Rolling-Metrics)[https://github.com/vladimir-bukhtoyarov/rolling-metrics]
