### ISSUE TITLE
Reservoir values should be double

### ISSUE THREAD

**Issue by ghost** [dropwizard/metrics#1525]
Currently interface Reservoir has a method: 
`void update(long value)`
migrating to `double value` would extend the use `Reservoir` for stats purposes with real numbers, with no significative loss.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @alzkiria 

Keep in mind that this library is addressed for monitoring, not for data analytics. Could you point out in which cases you need to record ```double``` measures instead of ```long```?

**Comment by ghost** [comment]
Hi,
I know the library is intended for monitoring information, and most of the usage cases are related to long/integer values (times, sizes, ...). However once you have used Reservoir with times, it is natural to use it also to work with other numeric types instead of implementing a replica with doubles, in my case money/time distance (double with 2 decimals and double for hours with decimals). Clearly those variables can be easily transformed to long (and apply the inverse function later), but as there is not loss using double, it seems the natural choice for stats. It avoids using transformation, replicating the classes with doubles or adding a new external library.

**Comment by vladimir-bukhtoyarov** [comment]
Use cases that you described look like rarely used exceptions. I think that it is better to introduce two new entities DoubleReservoir and DoubleHistogram instead of changing the existing API because of backward non-compatible change will lead to the following problems:
* All third-party reporters will be broken
* All third-party Reservoir implementations will be broken.
* It makes it impossible to operate the most performant implementations of the Reservoir interface which uses logarithmic intervals in order to preallocate all memory structures at initialization time and avoid garbage allocation at recording and snapshotting time. So, it looks like their authors will prefer to stay with the legacy Metrics-Core version or even to make own independent fork.

So we are having too many risks with this proposed change because by introducing support for rare cases we are getting community split. I vote to just introduce to new interfaces DoubleReservoir and DoubleHistogram, and nobody will be affected by them if they are not used in a particular application.

**Comment by joschi** [comment]
Additionally to the arguments @vladimir-bukhtoyarov already made, I want to very quickly address this:
> but as there is not loss using double, it seems the natural choice for stats.

While `long` and `double` have the same size in Java (both 8 bytes), many arithmetic operations are slower with `double` values.
The `double` data type also loses precision with very large values which you don't have with `long`.

> in my case **money**/time distance (double with 2 decimals and double for hours with decimals)

To quote Oracle on this:
> As mentioned above, this data type should never be used for precise values, such as currency.

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

@alzkiria Could you please describe some of your specific use cases for a reservoir with floating point values?

**Comment by ghost** [comment]
Hi,
with respect to

> While long and double have the same size in Java (both 8 bytes), many arithmetic operations are slower with double values.

today with modern hardware those differences are not significative. In fact sometimes double can behave even bettern than long (like div). I found https://www.grey-panther.net/2016/08/benchmarking-the-cost-of-primitive-operations-on-the-jvm.html.
Do you have any moder reference pointing that double is consistently slower than long?

On the other hand, with respect to the Oracle statement

> As mentioned above, this data type should never be used for precise values, such as currency.

double has a precision of 1E-15, so as far as you do +,- and a few *, / it should not be a problem because the errors is going to be >>1E-2. The unique problem can appear with very large loops of *,/ op (or exp ^^). For exampe if you use longs as doubles (eg 1.0) you will not have any problem with integer operations (+,-). The problem you can have with decimals using double (computing mean, std) are already there, not new. On the other hand, double is far fast than BigDecimal or similar implementation for currency, so it is worth.

With respect to the `DoubleReservoir`, the good part would be to have exactly the Reservoir implemented for double, not only the interface.

**Comment by joschi** [comment]
@alzkiria Could you please describe some of your specific use cases for a reservoir with floating point values?

**Comment by ghost** [comment]
A good example is time distance usig a coarse time unit (hours or days).
You can always use a finer unit, like ms, an apply h -> ms and the inverse ms -> h, but it would be a good idea to avoid those transformations. I know this trick can be used in general to any double domain, but it would be good to use the Reservoir without tricks.

**Comment by vladimir-bukhtoyarov** [comment]
> With respect to the `DoubleReservoir`, the good part would be to have exactly the Reservoir implemented for double, not only the interface.

Exactly. DoubleHistogram, DoubleReservoir, and DoubleSnpashot interfaces are meaningless without real implementations. In my opinion acceptance criteria for supporting doubles should be the following:
* Existing ecosystem are not broken, nothing should be changed for third-party extensions which do not need in this functionality.
* All reporters in the Metrics-Core repository must support exporting of DoubleHistogram.
* All five default reservoir's implementations such as ExponentiallyDecayingReservoir, SlidingWindowReservoir, SlidingTimeWindowArrayReservoir, UniformReservoir, SlidingTimeWindowReservoir must be reimplemented for doubles.

I can provide initial pull-request into 4.1-development branch because my company needs sometimes for this functionality(currently I solve this problem in a different way), but the amount of work does not look small, those before doing this I need to be sure that this request can be accepted to 4.x branch. @joschi what do you think?

**Comment by joschi** [comment]
Sorry for the late reply.

> I can provide initial pull-request into 4.1-development branch because my company needs sometimes for this functionality(currently I solve this problem in a different way), but the amount of work does not look small, those before doing this I need to be sure that this request can be accepted to 4.x branch.

@vladimir-bukhtoyarov I appreciate your offer! With the new functionality providing a rather big surface in the metrics library, I would consider adding such a pull request to Dropwizard Metrics 4.2.x. Does this make sense to you?

This would probably also address #863, wouldn't it?

**Comment by vladimir-bukhtoyarov** [comment]
@joschi 

I will try to accomplish this in the scope of ```4.2```
I have two questions:
* Do we have a hard date of this release?
* I have not found ```4.2-development``` branch.  Which branch should be used as a base for this feature?

**Comment by joschi** [comment]
> Do we have a hard date of this release?

No, it's done when it's done. There is also no big roadmap for Dropwizard Metrics 4.2 yet.

Given the distribution of Dropwizard Metrics versions (https://twitter.com/dropwizardio/status/1259130162794373122), I'm currently not sure how much sense it makes to put a lot work into Dropwizard Metrics 5.0.x with a lot of breaking changes.

> I have not found `4.2-development` branch. Which branch should be used as a base for this feature?

I've just created the [`release/4.2.x`](https://github.com/dropwizard/metrics/tree/release/4.2.x) branch you can base your branches on.

**Comment by joschi** [comment]
@vladimir-bukhtoyarov @alzkiria Did you have any chance to start working on this?
