### ISSUE TITLE
JMXReporter's path in release 4 is different to version 3.2.x

### ISSUE THREAD

**Issue by iandebeer** [dropwizard/metrics#1581]
The path to the JMXReporter differs between the the 2 versions: 4.0.5 uses: com/codahale/metrics/jmx/JmxReporter whereas 3.2.2 uses: com/codahale/metrics/JmxReporter. Not sure why you decided to that, as this breaks backward compatibility.

**Comment by joschi** [comment]
@iandebeer Thanks for reporting this!

The JMX reporter was moved ~3 years ago in 373d5b1c6c9d14b5c2ee590f2b3cefaac877549f (with follow-ups  a0aef506a73940174978289ab2cedfe30e2d6f26 and 67821418dcf4941f340f2b068cee1bfaff3ac3ff) and is for sure a breaking change.

But since it was done as part of the major version change (3.x -> 4.0.x), I think that's okay.

I'm hesitating moving the class back for compatibility with Dropwizard Metrics 3.x, because the 3.x branches are unmaintained quite long already and backward compatibility between Dropwizard Metrics 4.0.x and 4.1.x was maintained.

It's also a good preparation if we ever wanted to make Dropwizard Metrics compatible with the Java Platform Module System (JPMS) which doesn't allow split packages between modules, which was the case before. 

What do you think?

**Comment by joschi** [comment]
@iandebeer Also, if you plan to move from Dropwizard Metrics 3.2.2 to another version, I would recommend the latest stable version (4.1.7), because Dropwizard Metrics 4.0.x is not maintained anymore.

**Comment by iandebeer** [comment]
I am not using DropWizard directly, have a problem with transitive dependencies on Cassandra libraries. I am using JanusGraph with Cassandra as a backend store and also Akka Cassandra Persistence. The former uses version 3 of Dropwizard while the latter uses version 4. In my project the older dependency is evicted by the build tool (SBT) and then it breaks in runtime when it tries to access the JMXMetrics class.

**Comment by joschi** [comment]
@iandebeer I guess your best chance of fixing this is notifying these projects and, if possible, provide pull requests to update to the latest supported version of Dropwizard Metrics.
