### ISSUE TITLE
SlidingTimeWindowReservoir getTick() can overflow and break

### ISSUE THREAD

**Issue by omerkudat** [dropwizard/metrics#515]
The getTick() function of SlidingTimeWindowReservoir uses a collision buffer to allow for measurements which are happening within the same "tick". The default Clock tick is provided by System.nanoTime().

Under certain circumstances, nanoTime() returns a long sufficiently large that when multiplied by the collision buffer, it overflow into a negative number. The next line in the function will then check whether the new tick (nanos \* buffer) is larger than the old and, if not, it will return oldTick + 1. Because of this, the getTick() function returns ticks which are always incresing by one, therefore distorting the window.

To fix this, I added an absolute offset value to the class. The offset value can be a final field which is initialized when the class is constructured or a static. Following each call to Clock.getTick(), we would reduce the return value but this absolute amount.

**Comment by ryantenney** [comment]
@victor-prp I've just committed a possible fix, as well as your test: d49489663c43aa29593a363a08d2dbb7dd2e3582, however the test now times out, instead of resulting in an assertion error.

**Comment by martinsmatthews** [comment]
We've seen exactly this in production, using > 3GB memory when we get an overflow (there are lots of metrics in there ;)). 

@ryantenney agree with your logic, I've tested your fix and it looks good to me - test case is here https://gist.github.com/martinsmatthews/c2f87b8ec90652b7e3a1

Let me know what you think.

**Comment by ryantenney** [comment]
@martinsmatthews Great test, thanks! I'll get that committed to the branch and merge it in.

**Comment by martinsmatthews** [comment]
Cool, we are going to monkey patch this in our production environments, but would be good to get a bona fide release at some point!

**Comment by mozotom** [comment]
Here's what I've done at my place that fixed it https://github.com/dropwizard/metrics/pull/931
We had this problem when physical server uptime was over 417 days - rebooting server, would restart up time for another 417 days, but we wanted a permanent fix, so I created this one.

**Comment by mozotom** [comment]
My original solution got shut down, so here's alternative: https://github.com/dropwizard/metrics/pull/932 If you want to keep your service running longer without OOM, consider smaller collisionBitwidth (like 4 instead of default 8 will give you 16 years, not one)

**Comment by Zvezdochet** [comment]
Got this problem on one of our servers too. As a quick fix we use [Clock  wrapper](https://gist.github.com/Zvezdochet/40261036af09c895921a87dc0b0cdf48) to make its tick values smaller. It doesn't actually fix the bug, but as our app get restarted much more often than servers it helps live with it.

**Comment by mozotom** [comment]
@Zvezdochet This will save you for 834 days of physical server up time. If your app happens to be up on 834th day, it will develop memory leak (basically, it will stop clearing values). It doesn't matter if you restart your app a day before. While most physical servers get restarted more often than every 2 years, some might not (like in my case). With over 1,000 servers that hardly ever get restarted this problem has been popping up constantly until I've implemented https://github.com/dropwizard/metrics/pull/931 Now it will take 300 years before problem happens again. If you're worried about loss of precision, it would take 1,000,000 entries per millisecond to corrupt it - with nanosecond precision, reading clock twice in a row will not return the same value, so I think we're safe on that.

**Comment by Zvezdochet** [comment]
App restart should help and it did. Basically my clock returns ticks since
app start.
And I.m not telling your fix is bad, it is just more convenient for us to
pass different clock than to use patched lib or reimplement sliding window
in our code.

**Comment by mozotom** [comment]
As long as your app doesn't run for more than 417 days between restarts, you'll be fine

**Comment by miccab** [comment]
Wouldn't be easier to have an alternative Reservoir which drains list of collected metrics only when getSnapshot is called?
Thus:
* no need to trim while update operation, so less overhead
* no OMM like in SlidingTimeWindow discussed here (assuming that reporter is enabled)
* once you tell Reporter to report every X time then for sure, it reports all metrics from last report up to now (easier to interpret)

Things to note:
* Of course, prerequisite would be to have at least one reported enabled - otherwise OOM occur. But that is normal case to have such.  Alternatively, there could be some safety net if really needed (max queue size or periodic cleanup).
* Of course then you cannot have many reporters (as one would cleanup the data for the other): but then one can introduce a composite reporter. which would  be anyway more efficient to call getSnapshot once and reuse it instead of calling it many times.
* Problem would be with reporters like JMX, which exposes individual attribute of a metric (like p99), and each access goes via getSnapshot method, which would not work with this reservoir.  So well, JMX would not be compatible.

Not sure if that reservoir was ever considered?

**Comment by ho3rexqj** [comment]
I'm not sure why this issue was re-opened - the existing fix in commit 2156faf42201eb1ceba664b78088393f5bf26df2 seems adequate.  I'm reasonably certain Java guarantees integer operations on longs will use two's complement arithmetic, and as such it will always be true that `(timeOneInNanos*256) - (timeTwoInNanos*256) = (timeOneInNanos - timeTwoInNaos)*256`, even when those operations overflow.  If that's not the case would someone mind pointing out what I'm overlooking?  For example, perhaps the Java language specification does not guarantee integer overflow operations are well-defined (I couldn't find anything immediately definitive there, but I would be surprised).

There *is* a related issue not covered above that has to do with how the reservoir is cleared as part of a `trim` operation.  The sliding time window clears values from the map before `getTick() - window` - that works if the `getTick` is strictly increasing, but not if it's allowed to overflow.  I would expect the exiting implementation (that is, v3.1.0 onwards) to leave part of the window at the overflow threshold behind indefinitely.  I've added a pull request with a suitable fix - #1063.

**Comment by ho3rexqj** [comment]
There is still a bug in `getTick` that would produce behavior described above - the time difference between subsequent ticks may overflow, so that (effectively) `(nanoTime() - previousTime)*256 < 0`.  However, to produce that behavior `Long.MAX_VALUE/256+1` nanoseconds (~417 days) would need to pass between two consecutive calls to `getTick` - that is, ~417 days would need to pass without a call to `update`, `size`, or `getSnapshot`.  It seems unlikely that was the reason this issue was reopened, or the cause of any of the behaviors described above.

Never the less, that bug should be addressed as well.  The best way to do that, in my opinion, would be to restrict the next tick selected in `getTick()` to values between `nanoTime()*256` and `(nanoTime()+1)*256` (inclusive).  More than 256 updates at the same `tick` value in `getTick` (maybe several thousand cores are updating the reservoir concurrently?) would then loop back over that range, rather than adding values to subsequent nanosecond "blocks".  The following would produce the desired behavior there:

```
private long getTick() {
    for (; ; ) {
        final long oldTick = lastTick.get();
        final long tick = clock.getTick() * COLLISION_BUFFER;
        // ensure the tick is strictly incrementing even if there are duplicate ticks
        final long newTick = ((tick ^ oldTick) >>> 8) != 0 ? tick : oldTick + 1;
        if (lastTick.compareAndSet(oldTick, newTick)) {
            return newTick;
        }
    }
}
```

Note that the above implementation allows one tick value to overflow into the next block - the sequence in which `clock.getTick()` returned 0 would be `0, 1, 2, ..., 255, 256, 0, 1, ...` rather than `0, 1, 2, ..., 254, 255, 0, 1, ...`.  I couldn't find an efficient way to restrict values to the second sequence - branching or additional masking was required.  Maybe someone better at bit-twiddling than I am could find a better way to do that?

Finally, if the above and the fix proposed in #1063 are adopted, please note that `testGetTickOverflow` needs to be updated to allow a slightly wider window - the two `isLessThanOrEqualTo(window * 256)` statements in that method would need to be replaced with `isLessThanOrEqualTo((window+1) * 256)`.

**Comment by arteam** [comment]
I believe this should not be closed, because  @ho3rexqj wanted to create another pull request with a fix for the `getTick`  method (for the case with the long overflow during the calculation of a new tick).

**Comment by jplock** [comment]
Oops, sorry about that.

**Comment by ho3rexqj** [comment]
I'm afraid I likely won't be able to submit any new patches for the next couple weeks here (unrelated constraints).  Feel free to add the patch I posted above or something similar to the project yourself, if you get the chance.  Note that `COLLISION_BUFFER` and the shift width (`>>> 8`) are coupled (`COLLISION_BUFFER = 1 << 8`), and the constants should be updated to reflect that.
