### ISSUE TITLE
Let user choose whether to reset all metrics on GraphiteReporter start

### ISSUE THREAD

**Issue by zayim** [dropwizard/metrics#709]
Currently, when I start GraphiteReporter it resets all metrics, meaning if I call e.g. 'counter' method on MetricRegistry for some name, it will create new counter and set its value to 0, regardless if there is existing metrics with that name on Graphite. It is OK for most purposes, but I want to be able to override this behaviour, e.g. to set some flag in GraphiteReporter builder (example taken from [Dropwizard Doc Page](https://dropwizard.github.io/metrics/3.1.0/manual/graphite/)):
``` java
final GraphiteReporter reporter = GraphiteReporter.forRegistry(registry)
                                                  .prefixedWith("web1.example.com")
                                                  // ...
                                                  .resetMetrics(false) // THIS WOULD BE FINE TO HAVE
                                                  // ...
                                                  .build(graphite);
```

and if it is set to false, I would like for reporter to first check if metrics with given name already exists on Graphite before creating it and setting it to 0 (in case of counter, but similar applies to all metrics).

**Comment by xnejp03** [comment]
Yeah, something like this would be useful. We lose counters on the app redeploy, which can happen pretty often in a CI work flow. Keeping it on the current value would be really nice.

**Comment by saveveltri** [comment]
I agree with @xnejp03 and @zayim  . It would be nice to have "stateful" counters, not only for GraphiteReporter but also for CsvReporter for instance

**Comment by stevehu** [comment]
This issue has been opened for a while and it is still not resolved for it is not easy. I have similar requirement to reset counter during server startup so that my counter won't be lost during server start/stop. My understanding is graphite is a socket you can write into and you cannot query against it. In order to get the current counter, you have to query the influxdb (assuming your are using it) to get the current counter. I am wondering if someone has done something similar or I will start to explore it.

**Comment by ryantenney** [comment]
Closing as can't fix.
