### ISSUE TITLE
Possibility to set TimeUnit in Meter

### ISSUE THREAD

**Issue by jelgh** [dropwizard/metrics#710]
Hi,

I'm trying to upgrade from `Dropwizard 0.6.1` to `Dropwizard 0.7.1`. I'm having troubles when migrating from the old Metrics to the new ones, in particular with `Meter`. Previously we had the opportunity to set a rate unit, a `TimeUnit`, see [this code](http://grepcode.com/file/repo1.maven.org/maven2/com.yammer.metrics/metrics-core/2.2.0/com/yammer/metrics/core/Meter.java). I cannot see that this has been implemented in the new metrics; instead it has been hardcoded to `TimeUnit.SECONDS`.

Why was the opportunity removed? Or has it been replaced with something else? Can I do this setting somewhere else?

Best regards,
Johannes

**Comment by areddy7021** [comment]
Hi @jelgh and @ryantenney , i am facing the issue with the rate counts showing exponential values and my dashboard is getting broken while displaying metrics since it is accepting only integer not alpha numeric ..my rate count shows like this : 

"m15_rate" : 4.940272981828092E-9,
      "m1_rate" : 3.825709570901439E-96,
      "m5_rate" : 3.6172986715354425E-21,
      "mean_rate" : 2.7286933704633276E-4,

Any suggestions ..how can i parse the above string ?

**Comment by ryantenney** [comment]
What dashboard are you using? This isn't alphanumeric, it follows the JSON standard for floating point values: http://jsconsole.com/?parseFloat(%222.7286933704633276E-4%22)

**Comment by areddy7021** [comment]
I am using Logic Monitor widgets

**Comment by ryantenney** [comment]
I'm afraid I can't be of any help with Logic Monitor, all I can do is assure you this is a standard format for representing floating point values.

**Comment by areddy7021** [comment]
There is no way of doing any customization on these values to represent the exact value ?

**Comment by ryantenney** [comment]
These do represent the exact value. You can copy the reporter/metrics servlet and modify it if you need a non-standard output.

**Comment by areddy7021** [comment]
thank you @ryantenney ..so you mean writing my custom reporter and metrics servlet and using that. i got it.

**Comment by areddy7021** [comment]
@ryantenney : i have another scenario where i am really having hard time to figure out the best solution : I am monitoring one of the  nosql data stores by inserting and querying some of the requests to the cassandra ring. i have to show the inconsistencies occured and errors occured while doing that ..so the issue is the count keeps on going high in the widget where jmx property of count is really keeping that value even if one inconsistency occurs : for example : at some point of time there is one inconcistency and later the other inconsitency came up and now the value through jmx mbean count is 2 since the graph in LM always goes on to increase mode rather than spiking. so that means i have to reset the value to zero immediately after the inconsistency happened...instead i should not keep on adding to the inconsistent mbean value.so whenever the inconsistency occurs ..it should spike other than it should default to zero or any min value. for this type of change where do i really need to reset the mbean count for every event which i trigger ?
