### ISSUE TITLE
Store total elapsed duration for a Timer

### ISSUE THREAD

**Issue by slovdahl** [dropwizard/metrics#712]
I would find it useful to have the total elapsed duration for a Timer instance available. Then it would be possible to eg. calculate the average for all timed events. I'm well aware of how inaccurate an average can be, but that's also the case for Histogram snapshots when sampling reservoirs are used.

It could easily be solved by adding a `Counter totalDuration` to Timer. I'd be happy to implement it and submit a pull request if you find it useful as well. Otherwise I guess I have to keep building metrics-core myself.

**Comment by mchaabouni** [comment]
@slovdahl is this going to be merged with master and pushed to Maven Central?

**Comment by slovdahl** [comment]
It doesn't look like it will. And I don't have any power to choose what's merged, I'm just a normal user :)

**Comment by ryantenney** [comment]
Metrics and reporters are about to be overhauled in v4, and once that is complete it should be possible to override any meter to include arbitrary attributes, and have any reporter report them. Unless I see a lot of demand for this enhancement I can't justify adding it. I'll leave it open to gauge demand for it.

**Comment by slovdahl** [comment]
Sounds nice! Any kind of ETA for v4?

**Comment by pstibrany** [comment]
I would also be interested in this. The reason is that I'm exporting metrics to Prometheus, and I'd like to export timers as "summary". For summary, Prometheus expects "sum", "count" and quantile values (see http://prometheus.io/docs/instrumenting/exposition_formats/). Timer already gives me count and percentiles, but not total sum.

**Comment by hashbrowncipher** [comment]
@slovdahl, I have taken the liberty of PRing your changes in #1022, and wanted to make extra certain you were notified.

**Comment by slovdahl** [comment]
Awesome, thank you!

**Comment by mevdschee** [comment]
I would (also) love to see a sum of all the values.. next to the count..

**Comment by perlun** [comment]
This has been mostly fixed, #1254 has us covered. But this only covers the (unreleased) 5.0 branch of Dropwizard.

@arteam I presume the chance of seeing this backported to a 4.2 or 4.3 release isn't that big? We currently have a custom build (local package with the modifications done by @slovdahl) of Dropwizard "just because of this", and it would be much nicer to just be able to go with the upstream packages.

If it helps, I could gladly do the work of backporting it. I just want to ensure that it'll be approved before I spend the time doing it, to avoid wasting everybody's time.
