### ISSUE TITLE
HealthCheck returns 500 on unhealthy result

### ISSUE THREAD

**Issue by AndrewNorman** [dropwizard/metrics#766]
The current version of dropwizard that I am using 0.7.1.

If you write a HealthCheck that is healthy then the servlet returns a 200 code, which is fine.

If there is an unhealthy result then the servlet returns with a 500.

The problem is that a 500 indicates an "Internal Server Error" whereas I have a requirement that it should return a 503 meaning "Service Unavailable".

I think the 503 is a more appropriate response code than a 500, because at the moment I cannot tell the difference between a severe server issue (which is returning a 500) and a unhealthy service which maybe operational with restrictions (which are made clear in the HealthCheck response text).

**Comment by McPringle** [comment]
I would not recommend returning a 503 if you are not 100% sure that the check is not failed because of an internal server error. But you could simply extend the servlet and overwrite the `doGet` method:

```
public class MyHealthCheckServlet extends HealthCheckServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        super.doGet(req, resp);
        if (resp.getStatus() == HttpServletResponse.SC_INTERNAL_SERVER_ERROR) {
            resp.setStatus(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
        }
    }
}
```

**Comment by AndrewNorman** [comment]
That is pretty much the approach that I have taken. But it would be nice to have this as a configuration option for unhealthy check.

The server should return a 500 if there is an internal server error and this should not affect that at all.

**Comment by daluu** [comment]
I came across this as well today. In a way, it makes sense, but also is a bit confusing, but partly due to the limitations of the HTTP status code specs I think.

If one implements multiple healthchecks in a single health check (web) endpoint, if any one health check fails, you get an HTTP 500. This makes sense when one is being strict about health checks, but if one's criteria is more lax (say if less than X healthchecks fail it's ok, or if certain ones fail, it's ok), then this becomes a false alarm.

In any case the end result for detailed check is to check the response message/content rather than the status code for details on what failed exactly.

What makes this also interesting is that because the content is just JSON text for both pass/fail, to a user using a web browser to hit the endpoint, they have no idea about the HTTP 500 or other status code since it all looks the same (as a 200 ok) unlike the common response pages/output one gets on a 5xx or 4xx error. You only notice this peculiar behavior when using a specific web/REST client (`curl -I url`, wget, any REST client app/lib)

How do (most) people use the healthcheck web endpoint specifically? This could warrant some discussion on how it should behave, if HTTP 500 isn't the best behavior.

Also, is this documented somewhere? I wasn't aware of this behavior when I implemented healthchecks, or I overlooked it reading this: http://metrics.dropwizard.io/3.1.0/manual/healthchecks. Having to dig further into the docs or code to confirm that is rather additional work to a new user. Better we document it clearly somewhere that's easy to access.

**Comment by osigida** [comment]
@daluu, if health-check fails, the app should not be used, as it could not serve response properly.
example: connection to db, if it does not work, then it has no sense to try to use the app, it is broken.

So if you have multiple health-checks in the app and some of them fails but some not and it is still has some sense to call the app, then I think you have overloaded micro-services and it should be split into smaller services. 
Or health-check was implemented wrongly and it is not really critical and should be excluded from health-check cycle.

**Comment by dantheman46** [comment]
I think that If one implements multiple healthchecks in a single health check (web) endpoint and one of these checks returns false whole health check should return false - HTTP 500 - not 200

Do you plan to implement this feature?

Many software validate health using http status codes.
In this case this library is useless

We need this feature and we would like to know if we have to find another solution or wait for this feature

Many

**Comment by daluu** [comment]
@dantheman46, have you tried the suggested workaround from @McPringle? And can you elaborate on your comment? Are you in a situation as I am with implementing multiple health checks in one endpoint where it's ok for certain health checks to fail?

@osigida, what you mention is logical. However, I'm not building a microservice, rather it's a tool to help test microservices. In a perfect world, the microservice monitoring would be enough that we don't need to monitor with separate tooling, but alas, not there yet. The health check for this tool in a way could be similar to a test tool/framework test result output, which ideally would also be an overall fail if any one test fails, but due to what we are able to effectively inject in the system (it's not 100% deterministic to produce the same results all the time), the health check is thus not perfect. You could say I should remove the flaky checks but I find it may be useful for monitoring (as stats). Also, I have metrics endpoint for the tool as well, for which the health checks are all based on. But the health check endpoint makes it easier for new users or a novice to glance over than to view the list of metrics and manually do correlation on them (as the healthcheck does that for you). You could say I have an unconventional use case of the metrics/healthcheck library, but then again no one said this library is "only" for microservices, if I'm not mistaken.

**Comment by daluu** [comment]
Oh darn, I (at least) missed the notification for this somehow. I guess nothing but to open new issue for this if there's any concern for it from the public, since (I) can't reopen it.
