### ISSUE TITLE
HealthCheckRegistry.runHealthChecks(ExecutorService) support for Timeout

### ISSUE THREAD

**Issue by nerdynick** [dropwizard/metrics#790]
It would be nice to have another method on HealthCheckRegistry that runs the HealthCheck's via an ExecutorService but supports a configurable timeout for each Future.get(). If the timeout happens then it reports the healthcheck as unhealthy.

We experience on occasion where some libraries' HealthChecks will take awhile or block for an extended period of time when the service being checked is actually in a bad state. When this happens we see a pile up of connections from our Proxies and Nagios systems waiting for the check to return or their http timeouts failing. It would be ideal for for the HealthCheck systems to optionally fail-fast in these state.

I do believe the be all solution is to contact the libraries developers or file a bug to create a better HealthCheck that doesn't block for a large amount of time. However that can take some time to get implemented and released. This would be a safety measure until a fix can be put in place into the main library.

**Comment by lidel** [comment]
I strongly agree. 
Execution of `HealthCheck#check()` method should always be wrapped in a timeout.
Things break and without timeout you won't ever know it.

Actually,  PR https://github.com/dropwizard/metrics/pull/330  introduced custom implementation of `HealthCheckRegistry` that had this very feature:

https://github.com/dropwizard/metrics/blob/121c2e78036176ecb9e805ac011a6c757cd83adc/metrics-core/src/main/java/com/yammer/metrics/core/ParallelHealthCheckRegistry.java#L47

I  inspected  `metrics-code-3.2.2` and `metrics-healthchecks-3.2.2` and I don't see this class anymore.

The default implementation of `com.codahale.metrics.health.HealthCheckRegistry#runHealthChecks` will block forever:

https://github.com/dropwizard/metrics/blob/66b29bec376047b5dbe462c2ee89116b3d98c9e3/metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java#L229

I see two ways to time-box execution of `check()`:
- create customized  `HealthCheckRegistry` (or copy one from PR #330)
- execute `runHealthCheckscustom` with  `ExecutorService` that is cabable of cancelling jobs after a timeout

Quick PoC for first approach:
```java
    private static abstract class HealthCheckWithTimeout extends HealthCheck {

        private final long timeout;
        private final TimeUnit timeoutUnit;
        private final ExecutorService executor;

        public HealthCheckWithTimeout(long timeout, TimeUnit timeoutUnit) {
            this.timeout = timeout;
            this.timeoutUnit = timeoutUnit;
            this.executor = Executors.newFixedThreadPool(1));
        }

        protected final Result check() throws Exception {
            Future<Result> healthCheck = executor.submit(this::checkWithTimeout);
            try {
                return healthCheck.get(timeout, timeoutUnit);
            } finally {
                healthCheck.cancel(true);
            }
        }

        protected abstract Result checkWithTimeout() throws Exception;
    }
```

Usage: 
```java
                new HealthCheckWithTimeout(5, TimeUnit.SECONDS) {
                    @Override
                    protected Result checkWithTimeout() throws Exception {
                        // check code
                    }
                }
```

**Comment by arteam** [comment]
It was basically the approach implement for database healthchecks in Dropwizard: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-db/src/main/java/io/dropwizard/db/TimeBoundHealthCheck.java.

I think it would be nice to have such a class in the core library. On the other hand, Dropwizard since 3.2.0 supports async health checks which could be used to mitigate the issue of expensive health checks.

**Comment by lidel** [comment]
It would be great to have both `TimeBoundHealthCheck` and unbound `HealthCheck` in `metrics-core` .
Is such PR welcome? (_**Disclaimer:** I no longer work on this, so it is up for grabs!_)

As for mitigating the problem with async checks:  I would be careful with that. 
My understanding is that `@Async` checks are not time-bound right now, which makes them very, very dangerous. When something goes wrong async check can hang forever and not only waste resources but give false sense of safety: due to async nature reading it will return previous (usually healthy) result.

**Comment by arteam** [comment]
> It would be great to have both TimeBoundHealthCheck and unbound HealthCheck in metrics-core .
Is such PR welcome?

Yes, such a PR would be certainly welcome!
