### ISSUE TITLE
Custom MetricSet only called once

### ISSUE THREAD

**Issue by tbrizard** [dropwizard/metrics#798]
I'm observing a strange behavior when implementing the MetricSet interface.  Essentially the "getMetrics" method only gets called once.  I've searched the existing issues, looked at other implementations of the MetricSet interface, etc. and cannot find any mention of this specific issue.

I'm using other MetricsSet implementations, like "com.codahale.metrics.jvm.MemoryUsageGaugeSet" and they work fine. 

Below are code snippets.  Any help would be appreciated.

```
 <metrics:register metric-registry="metrics">
        <bean metrics:name="jvm.gc" class="com.codahale.metrics.jvm.GarbageCollectorMetricSet" />
        <bean metrics:name="jvm.memory" class="com.codahale.metrics.jvm.MemoryUsageGaugeSet" />
        <bean metrics:name="jvm.thread-states" class="com.codahale.metrics.jvm.ThreadStatesGaugeSet" />
        <bean metrics:name="jvm.fd.usage" class="com.codahale.metrics.jvm.FileDescriptorRatioGauge" />
        <bean metrics:name="hystrix.metrics" class="com.mycompany.util.metrics.HystrixCodahaleMetricSet" />
    </metrics:register>
```

```
public class HystrixCodahaleMetricSet implements MetricSet {

  @Override
    public Map<String, Metric> getMetrics() {

        final Map<String, Metric> gauges = new HashMap<String, Metric>();

        // code to add gauges left out for brevity, but is similar to that in the MemoryUsageGaugeSet class

        return Collections.unmodifiableMap(gauges);
}
```

**Comment by ryanrupp** [comment]
MetricSet.getMetrics() will only be called once when registering the metrics via the MetricRegistry so this may be the expected behavior, see here - https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L385 - so if the MetricRegistry is told to register a MetricSet (via MetricRegistry.register) it checks if it's a MetricSet and if so just calls getMetrics() once on it to get the set of metrics and registers each one. After that getMetrics() on your registry set will probably never be called again (unless your own code is doing something), instead you'll just have all your gauges invoked directly e.g. if reporting or accessing the gauges via JMX.

Do you see the metrics being registered via JMX?

**Comment by tbrizard** [comment]
That was the piece I was missing (i.e. gauge instances are registered and then called directly).  Thanks Ryan!!

**Comment by ryantenney** [comment]
Thanks @ryanrupp!
