### ISSUE TITLE
Configurable metric rates and quantiles

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#812]
On the fence about this.

**Comment by remen** [comment]
Personally, I would *love* to have a way for meters/timers to show the rate averaged over the time period since the last time it was *reported*.

I.e., sending metrics to graphite once every 10s, I would like to publish average rate over the previous 10s. Currently, as far as I've understood from the source, that would require a custom *reporter*. A nicer option, imo, would be a way to have a configurable rolling window average within the meter.
