### ISSUE TITLE
Metric event streams

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#822]
Provide an interface through which a listener can be registered to receive MetricEvent objects that match a MetricName query. MetricEvent would include the time and type of event (Timer, Meter, Counter, Histogram) and the associated value (timer=time, meter and counter=count, histogram=value).

**Comment by felixbarny** [comment]
Sounds cool. What is it good for?

**Comment by pvalsecc** [comment]
Example of use case:
Integration with statsd.
The current implementation doesn't send timer events right away but, collects them for a given period then sends 10 messages to statsd (max, mean, min, stddev, ...). This is not very well integrated with my other statsd metric coming from other softwares.

Having such feature would allow a better statsd integration.

**Comment by marshallpierce** [comment]
This would be pretty expensive for frequently updated metrics, though (it allocates, for instance). While a useful feature, I'm not sure that it should be part of the typical Meter, etc, types since those are all about local aggregation and occasional publishing of batches of data. Perhaps this is a separate use case that deserves a separate set of types.

**Comment by pvalsecc** [comment]
Proposal here:
https://github.com/pvalsecc/metrics/tree/streaming

**Comment by jmason** [comment]
if a metric-recording event suddenly starts happening more frequently than usual, this risks exceeding the bandwidth available for the listener (or the upstream service ie. statsd).  It may be a good idea to have some way to drop limit-exceeding updates from the stream, and/or support approximation or sampling.

**Comment by pvalsecc** [comment]
@marshallpierce: saying something is expensive without actually trying can be surprisingly wrong in computer science. For example, your statement "it allocates" is invalid in the context of performance. Since java 1.7 (available but disabled in java 1.6), the JIT is doing escape analysis and uses the stack or even the registers for storing temporary objects. Therefore, nowadays, allocation doesn't necessarily mean bad perfs.

@jmason: this is more a problem of the "plugin" using the event system to send them to another service. For example statsd uses UDP. If you put the socket in asynchronous, the OS or the network is going to drop some stats for you if it becomes too busy. But since UDP doesn't have any congestion control, unlike TCP, you may put your network to its knees. But still, IMHO, it's not the business of the event system within Metrics.

**Comment by marshallpierce** [comment]
@pvalsecc EA is quite limited in its applicability in the JVM. I would be cautious (especially in a library like this, not a full service that can more tightly control its runtime environment) of relying on it, even if it turns out to be applicable in some setups.

**Comment by pvalsecc** [comment]
@marshallpierce, OK. Look at my proposal and point me to the places it adds significant performance problems for users not using the StreamingMetricRegistry but only the MetricRegistry.

**Comment by marshallpierce** [comment]
@pvalsecc Not sure if it's intentional but you're coming off as a bit hostile.

You've made `Timer.update` bimorphic, which has a small performance cost, but you've also created the opportunity for people's measurement-gathering code to be arbitrarily slow because it calls all of the listeners inline. Generally it's best to try to separate the "acquire the measurement" path (which is presumed to be hot) from the "do stuff with the measurement" path to avoid perturbing the system being measured.

**Comment by pvalsecc** [comment]
@marshallpierce, hostility not intended. Sorry if I made you feel that and thanks for telling.

My usage of Metrics is maybe atypical, but I measure stuff in the range of 20ms. So, a bimorphic call is totally negligible compared to that. And it's as well very negligible compared to all the locking happening in the Reservoir used by the timer.

Now about the decoupling. IMHO this would be overkill and counter productive for a few reasons:
* You would have to use some queue which as some performance cost (contention and memory allocation on the heap because of the escape).
* Handling stuff in another thread is quite costly as well (context switches, harder strain on the caches).
* The libs that sends those events to other system most likely already have this decoupling (the statsd one I use has it).
* I'm a big fan of the KISS principle.
* you can always document in the event handler that processing in there must be extremely short.

I can understand that if you send events every 10ns, those streaming events are a no go. But for people like me (around 20 events per seconds) it would be a nice feature.

Another solution would be to merge the small changes I did in the com.codahale.metrics package and move the com.codahale.metrics.streaming package to a plugin. That way if the user doesn't want streaming events, he doesn't load the streaming plugin JAR and the JIT will be able to inline Timer.update (for example) as before. Zero impact for "nanoseconds" people and "milliseconds" people would be able to stream events like happy campers.

**Comment by marshallpierce** [comment]
You're still conflating "locally aggregate these things" with "stream them live to some other thing". These are two totally separate concepts, and they're now hidden behind what looks like a Timer. 

If you want to live-stream measurements to some other system, it shouldn't be in the Timer class (or any other existing metrics type).

**Comment by ryantenney** [comment]
You're absolutely right. What's the point of any of the existing meter types if not aggregating locally? This is also beneficial as it will be much easier to implement.

**Comment by bentatham** [comment]
To me, whether the Timer (or any other metric) locally aggregates or streams live should be independent of the interface contract of that metric.  In library code, you just want to "record" how long some activity took, etc.  Similar to logging, you don't care what appenders do with the messages in your code - just that you logged something - and the system decides at higher levels what to do with it (write to file, stream to ELK stack, etc).  Same here - you record a time, and if that gets aggregated with meters, etc or the raw value streamed out (assuming little to no performance impact on the calling thread), or both, then that is all good.   It allows us to decide later what to do with the metrics we report when we're actually running the system instead of when we're writing the code.

I don't think anyone would suggest doing network IO to stream out a metric on the calling thread -- IO should be batched up (I like the way influxdb-java does it).  And there is plenty of overhead in doing the aggregation too (lots of memory, synchronization, etc) that has performance hits too.

I agree that live-stream of measurements should not be in any of the metrics classes themselves - it should all be decoupled with observers.   To me, even the aggregation of the data could be done in observers too, letting the front end Metric classes (interfaces) be used in the libraries, decoupled from their backend implementations of what to do with those metrics.  

Getting back to the original proposal of this issue by @ryantenney, I like the idea of an ``MetricEventListener`` interface.  I would take it one step further, and make the current "aggregating" implementations be a listener as well - in other words, the update, tick, mark, etc methods of the metric classes would just notify their listeners and that's it.  Then the user has complete control over what they want - aggregating vs streaming vs whatever else they want to implement.  To give full flexibility, we could provide both synchronous and asynchronous listeners within the metrics framework, so the metric library would take care of the queue/threading for the async case (for listeners that might need a bit more time to run, IO, etc).

Doing it this way also allows turning off metrics completely, which may be useful in some systems to reduce overhead without having to change library code.  Again, I envision this like a logging api.  Wouldn't it be great if there were some standard "metrics" api (like slf4j) that lots of libraries could use, but then you configure in your application what to do with it (or nothing).  All it would take in the metrics library is to turn the existing Metrics classes (the ones with the mark, increment, update, etc methods) into interfaces and turning the "get" Metric interface into ``MetricEventListener``'s instead of the metrics themselves.

**Comment by marshallpierce** [comment]
I would not want a library that does this because it would be so unpredictable, but you obviously do and that's fine. However, it's a completely different thing than what Metrics currently does, and it would be pretty unkind to users to radically change the meaning of a well-established class. Doing IO on the calling thread is pretty much what this opens the door to, and I would be surprised if users did not unwittingly do that to themselves if we give them the opportunity. 

If you want to have a separate set of classes for measurements that happen so infrequently that the performance considerations don't matter, I've got nothing against that, but I would much prefer to consume types that have known performance characteristics. I'm not sure what you're basing your performance numbers on but the current aggregation methods are very cheap indeed. LongAdder can handle hundreds of millions of updates per second for a Counter, and HdrHistogram is down in the several-ns-per-update realm too for Timers. Casually comparing this network IO overhead as if "that's a problem too" is, well, apples and oranges

If this were anything other than a library used to measure performance that therefore should avoid skewing the measurements itself, I'd be all for listeners and flexibility and abstractions. But, in this case, there is value in guaranteeing the high performance and consistency that we can achieve with local aggregation and occasional snapshots (ideally, deltas but that's another story).

It's conceivable that you could build something fast for streaming individual numbers (chronicle queue?), but it's unlikely to fare well against to `lock xadd` on x86, which is what LongAdder boils down to on.

**Comment by bentatham** [comment]
I think we agree more than disagree here.  We both want high performance as well as flexibility and abstractions.

My proposal is to keep the default behavior as it is, but make the current aggregations it into an observer pattern instead - so for the default case the extra cost is one extra method invocation (or perhaps an iteration over a set of listeners).  And that could likely be removed as well by making the whole listener thing optional to begin with.

I agree in terms of performance.  I would _never_ suggest doing IO on the calling threads.  And the rate of IO being called would also be configurable (as it is now in the reporters).    For my performance concerns, I think I was looking at the way the Snapshots are calculated on a Reservoir -- a sync block per array element in some cases -- but you're right, the performance of ticking a metric is the key thing to consider here, not the periodic reporting.  My bad.

> I would be surprised if users did not unwittingly do that to themselves if we give them the opportunity.

I agree, but at the same time think we need the flexibility anyways.  We can't protect everyone from themselves.  That's why I propose making very explicit listener registrations of synchronous vs asynchronous listeners - with very clear javadocs explaining why and the importance of throughput, not effecting the application threads, etc.  And we could use a high performance queue (like [disruptor from log4j2](https://logging.apache.org/log4j/2.x/manual/async.html#UnderTheHood)), but only enabled when there are actually some async listeners to worry about. 

In the end, my needs were driven by just wanting to turn off the percentiles in a Meter, but keep other parts of the statistics.  And it has evolved into thinking about the overall architectural picture.  Overall, I've been very happy with metrics, just would like more flexibility to choose how it works based on specific requirements.

**Comment by marshallpierce** [comment]
In my view, this sounds like you want the syntactic convenience of making one call and have it be both observer-style and plain-old-metrics style. AtomicLong, for instance, is not AtomicLongWithMaybeAnObserverAttached to it, because that conflates concerns -- regardless of the possible syntactic convenience of having one `compareAndSwap()` call inform some observer when it was called. The same applies here. If you want two different styles of functionality, and you don't want two method calls, then I think they should be wrapped in your own abstraction rather than bundling the functionality you want into the existing system at the cost of cohesion (and performance).

If you want one-by-one observer, you want a simple instance of the Observer pattern. RxJava may be suitable for your purposes, for instance. You don't need Metrics for that.

**Comment by vladimir-bukhtoyarov** [comment]
@pvalsecc similar to this https://github.com/dropwizard/metrics/pull/1091 your solution missed [registry](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L83) method which allow to add to MetricRegistry already instantiated metric, and this introduces following inconsistency:
- Metric which instantiated outside registry will produce zero event.
- Metric which created through one registry but also registered through "register" in another registry will notify listeners only for first registry.
