### ISSUE TITLE
JMX Refactor + Add healthchecks

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#832]
Extract JMX into a new module, and add HealthCheck support.

Contributions for this are welcome, it may not happen if I have to find time for it.

See #92 #149 #830

**Comment by jgangemi** [comment]
:+1: for continued jmx support.

it's used heavily at the day job and i find it extremely useful for random side projects.

**Comment by bripkens** [comment]
Same here! Having health checks available via JMX would enable us to easily extend our monitoring.

**Comment by ariens** [comment]
+1 for continued JMX support--came here specifically looking for health check support.

**Comment by gdubya** [comment]
+1 to what @ariens said

**Comment by ryantenney** [comment]
Alright, JMX definitely stays.

**Comment by sivasamyk** [comment]
I am trying to fix this issue. There are two options
1. Extend current JMXReporter with a new static forRegistry method with HealthCheckRegistry argument  and a new builder
2. A new HeathCheckJMXReporter class which will handle health check reporting.

I prefer option 1. Let me know your comments.

**Comment by CodingFabian** [comment]
on this high level both sound kind of like the same for me. The second one sounds a bit more decoupled.

**Comment by sivasamyk** [comment]
On exploring further I see that I cannot implement option#1 since health check is a different module. I am going ahead with option#2.

**Comment by bripkens** [comment]
Woah, this is great to hear @sivasamyk. Thank you very much! :)

**Comment by ryantenney** [comment]
Hi @sivasamyk! Thanks for working on this! I agree with option #2. If you aren't already I'd love to see JMXReporter and JMXHealthCheckReporter extracted to their own module, metrics-jmx.

**Comment by sivasamyk** [comment]
sure, let me try it

**Comment by sivasamyk** [comment]
Also moving JmxAttributeGauge class from metrics-core to metrics-jmx module. Any comments?

**Comment by ryantenney** [comment]
That's a tough one. Sure why not.

**Comment by robertjchristian** [comment]
Hi All,

Just checking in to see what the current status of "JMX support for HealthChecks" is.

I have a use case - use the Healthcheck module to expose a GREEN/RED/YELLOW-like status in JMX, with ability to manual re-run Health Checks from JMX console.  Keeping in mind that it can be expensive to run these tests, especially on a production system under load.

I'm considering using a Cache Gauge to work around the existing limitations.  This was suggested in a google groups thread that I'm now unable to find...

Any and all advice greatly appreciated.

Thanks,

Rob

**Comment by robertjchristian** [comment]
I found the post:

https://groups.google.com/forum/#!msg/metrics-user/-w4vMI_hKdE/UTXtdnzc7CcJ

I was just hacking around this very problem this week so I have a pretty good idea what is going on here.  

The JMX Reporter has to register mbeans for each value to report.  The central problem here is Healthchecks do not have a value.  Instead you need to execute a healthcheck, get a Result, and then publish the result.  One reason no one has coded this up is in many cases these checks are non-trivial and not something you want to run too frequently.  

In the end it boils down to : 
Metrics are a snapshot which can be published trivially.
Healthchecks are a test to execute with an undefined performance impact.
Once I understood the problem better I decided I did not want to publish my own healthchecks this way.  i chose instead to use a Console or Slf4jReporter (I wrote my own) because that also let me track healthcheck status over time.  Where JMX only gives you that if you have something attached and recording state when the problem occurs.  It is not as useful for debugging after the problem has occurred.

If you still wish to publish healthcheck but want to limit the published rate to reasonable frequency one workaround is to create a CachingGauge at the same time you create the healthcheck and use it execute the healthcheck and publish the state at a predetermined rate so that it can be viewed along side other metrics.  It isn't ideal but it is less work than adding HealthCheckRegistry Listeners, adding a new mbean for each healthcheck and dealing with possible performance issue of running checks frequently.

**Comment by vladhid** [comment]
What are the odds that JMX will see the 4.0 version? JMX reporting was found to be the most suitable in the situation with many little services for monitoring with Zabbix.
