### ISSUE TITLE
Hierarchical Structures of Metric Registries

### ISSUE THREAD

**Issue by wicknicks** [dropwizard/metrics#842]
In a project I am working on, we have multiple sub-projects each of which are independent libraries, and use codahale metrics to instrument their code, and report metrics. When integrated with the parent project, we have to add metrics from the child project registry to the parent registry. Currently, this is what we do:

`
parent.register("some-name", childRegistry); 
`

Since MetricsRegistry is an instance of MetricSet, it will read all the metrics that are available at the time of calling register. All metrics which are created later using methods such as (`counter()`, `histogram()`, `timer()` etc) are not going to be added to included in the parent registry.

Would it be possible to retain a reference to original child registry in the parent? When the reporters iterate through them, they can **recursively unroll** each child registry, and report them as well.

**Comment by ryantenney** [comment]
Help me try and understand your use case a bit better. The first thing that comes to mind is that you can set up a reporter for each of the metric registries, instead of merging all the registries and running only one reporter.

**Comment by wicknicks** [comment]
That's a good point. 

Our parent project has an HTTP endpoint which shows the current status of all metrics. Behind-the-scenes, it is a custom made reporter, which "prints" numbers in `<html>`.  Also, we have custom reporters which send the numbers over to TSDB. Having a single-point-of-contact reporter is beneficial than having multiple of them running in the background. Each time I add new a library/registry, I would have to update the reporter logic to write the `<html>`. If we can create hierarchies, then all it would take is one line of code:

`parent.register('prefix-for-all-metrics',  childRegistry)`

And we all the reporters which work on the parent registry will automatically pick up the new registry.

**Comment by wicknicks** [comment]
@ryantenney: any thoughts on this?

**Comment by ryantenney** [comment]
Your use case makes sense, but I'm going to leave this issue open to see if other people want to see this implemented before I commit to it.

**Comment by wicknicks** [comment]
Thanks very much, @ryantenney. BTW, I'll be happy to help you implement this.

**Comment by c2nes** [comment]
I think this is already _kind of_ supported. `MetricRegistry` implements `MetricSet` which means `register` will accept it and simply add all the metrics from the "child" to the "parent". However this only copies the metrics registered with the child at the time `register` is called on the parent. Any metrics registered with the child after this point will be unknown to the parent.

We use Dropwizard Metrics pretty extensively where I work and we've patched over this using a `MetricRegistryListener` which actively propagates metrics additional/removal from the child to the parent.

We've found this parent/child registry pattern useful for a couple reasons,

1. Namespacing. We can create a child registry under a prefix so we don't have to specify the prefix in each place we create/register a particular metric (a la top-of-class `Logger` declaration). We only need to specify the prefix once, when we create the child registry.

2. Incorporating external components. We have libraries which expose internal metrics through a `MetricRegistry` created by the library. By having the library manage its own registry we don't need to be concerned with piping a client-provided `MetricRegistry` + prefix through the library code.

In both of these cases we _could_ create a reporter per registry, but we find this is more cumbersome for us. Some of our `MetricRegistries` are created during runtime rather than bootstrap time. Its simpler for us to attach/detach these to a parent registry than to dynamically stop/start new reporters. We also commonly have multiple reporters (JMX and Graphite typically) so in these cases we would need to start/stop a new reporter of each variety for each registry created. Lastly, it is nice that with the Graphite reporter and a single registry that we only need to establish a single connection per reporting interval instead of one per registry.

I think a couple additional `MetricRegistry` methods could be useful for these purposes,

* `MetricRegistry usingNamespace(String name)` - This would return a view of the registry within a namespace. All register/add/get methods would implicitly use the namespace when delegating to the source registry.
* `void bind(String name, MetricRegistry child)` - This would attach the child registry to the parent. All existing metrics would be added with `name` used as a prefix (this much is the same as `register`). _Additionally_ all future modifications to the child will be reflected in the parent in the same manner.
* `void unbind(String name, MetricRegistry child)` - Undoes a previous `bind` call.

Thoughts?

**Comment by ryantenney** [comment]
@c2nes I like your proposal.

**Comment by randomstatistic** [comment]
For the record, I'm particularly interested in the idea of namespaced registries, and the usingNamespace method sounds like exactly what I want.

**Comment by wicknicks** [comment]
Really like the bind and unbind APIs proposed by @c2nes.

**Comment by veigap** [comment]
I also consider this really useful, it would be useful to have a tree of registries each one mapped to predefined prefix.

**Comment by henryptung** [comment]
@c2nes Makes sense, and agreed that this is useful. Would like to add though that I think `usingNamespace` and `bind`/`unbind` are redundant here; we should probably only use one or the other. Of these two, I think I like the latter slightly more, for a few reasons:

- If I understand correctly, the `usingNamespace` API implies the creation of a filtered view; there is still only one true `MetricRegistry`, but the view filters to metrics matching namespace (removing the namespace as it returns) and will also add metrics under the same namespace in the true `MetricRegistry`. This is reasonable, but would not allow incorporation of a pre-created child `MetricRegistry` instance, the way `bind`/`unbind` instance does (i.e. I would need to _inject_ my namespaced/filtered `MetricRegistry` view into the child, which may/may not be possible).
- `bind`/`unbind` is explicit about lifecycle, and allows clean detachment of child registries and metrics from the parent at will. No concerns about leaked `Metric`s hanging around before/after, etc.
- Reporters are clearly separated between parent and child, and semantics are "obvious" (at least to me, at the moment).

For the most part, if I understand correctly, `usingNamespace` could be approximated by creating a child registry, binding it with the appropriate namespace, and returning that.

As a side benefit, the separation of `bind` from `registerAll` also highlights the stateful vs. non-stateful nature of the two methods. As a tradeoff, it does seem like a `bind`/`unbind` API would have to be careful to avoid name collisions between parent and child registries (or else :fire:).

**Comment by laurentvaills** [comment]
Hi.

We're also interested by this feature. 
With my colleague @violette we ended with a sub class of `MetricRegistry` that subscribes a listener to a parent `MetricRegistry`.  Then the parent is notified when a metric is added or removed.
Here is how we plan to use it : 
```java
HierarchicalMetricRegistry rootRegistry = new HierarchicalMetricRegistry();
HierarchicalMetricRegistry childFoo = rootRegistry.child("foo");
HierarchicalMetricRegistry childFooBar = childFoo.child("bar");
```

Here is the class : 
```java
public class HierarchicalMetricRegistry extends MetricRegistry {

    public HierarchicalMetricRegistry() {
    }

    public HierarchicalMetricRegistry(String prefix, MetricRegistry parent) {
        addListener(new ForwardingMetricRegistryListener(prefix, parent));
    }

    public HierarchicalMetricRegistry child(String prefix) {
        return new HierarchicalMetricRegistry(prefix, this);
    }

    private static class ForwardingMetricRegistryListener implements MetricRegistryListener {
        private final MetricRegistry metricRegistry;
        private final String prefix;

        /**
         * Creates a new {@link ForwardingMetricRegistryListener}.
         *
         * @param prefix
         *     The prefix to link to, not {@code null}.
         * @param metricRegistry
         *     The parent {@link MetricRegistry}, not {@code null}.
         */
        public ForwardingMetricRegistryListener(final String prefix, final MetricRegistry metricRegistry) {
            this.prefix = checkNotNull(prefix);
            this.metricRegistry = checkNotNull(metricRegistry);
        }

        /**
         * Returns the fully qualified name of the object.
         *
         * @param name
         *     The name of the gauge, of the counter, etc.
         * @return The complete name of the Metric, such as 'foo.bar.quix'.
         */
        private String fullyQualifiedName(String name) {
            return prefix + "." + name;
        }

        @Override
        public void onGaugeAdded(String name, Gauge<?> gauge) {
            metricRegistry.register(fullyQualifiedName(name), gauge);
        }

        @Override
        public void onGaugeRemoved(String name) {
            metricRegistry.remove(fullyQualifiedName(name));
        }

        @Override
        public void onCounterAdded(String name, Counter counter) {
            metricRegistry.register(fullyQualifiedName(name), counter);
        }

        @Override
        public void onCounterRemoved(String name) {
            metricRegistry.remove(fullyQualifiedName(name));
        }

        @Override
        public void onHistogramAdded(String name, Histogram histogram) {
            metricRegistry.register(fullyQualifiedName(name), histogram);
        }

        @Override
        public void onHistogramRemoved(String name) {
            metricRegistry.remove(fullyQualifiedName(name));
        }

        @Override
        public void onMeterAdded(String name, Meter meter) {
            metricRegistry.register(fullyQualifiedName(name), meter);
        }

        @Override
        public void onMeterRemoved(String name) {
            metricRegistry.remove(fullyQualifiedName(name));
        }

        @Override
        public void onTimerAdded(String name, Timer timer) {
            metricRegistry.register(fullyQualifiedName(name), timer);
        }

        @Override
        public void onTimerRemoved(String name) {
            metricRegistry.remove(fullyQualifiedName(name));
        }
    }
}
```

**Comment by karlthepagan** [comment]
I'm interested in this feature. I would like to create a MetricSet where the members are dynamically discovered.

My use case is a count of active members in a table: `SELECT key, COUNT(id) FROM table GROUP BY key;`

I would like to avoid the complication of re-discovering new keys between deploys.

**Comment by joschi** [comment]
@karlthepagan @wicknicks Would you be able to provide a pull request for this feature?
