### ISSUE TITLE
add tag feature for meter

### ISSUE THREAD

**Issue by jiming** [dropwizard/metrics#877]
What about add tag feature in metrics? An example
```java
metrics.meter("requests").tag("userName", "jiming").tag("function", "pay").mark();


```

Later I can select the data by `userName=jiming` Or `userName=liu` ..., to filter the data. Kind of like sql.

Which is going to make metrics super powerful and helpful than ever.

**Comment by pparth** [comment]
+1. Dimensions would be very a very useful addition especially when using metrics for operational insight.

**Comment by ryantenney** [comment]
Already done the v4 branch

**Comment by jiming** [comment]
hi Ryantenney,

Any plan for v4 release? Or could you please tell me which class is the one you done in master? Eagerly to see the feature!

Thanks a lot and have a nice day!
Jiming

**Comment by ryanrupp** [comment]
The class is MetricName which has the concept of tags for dimensions, see [here](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricName.java#L52) - then the MetricRegistry uses MetricNames instead of Strings for the keys, for instance [here](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricRegistry.java#L100) - you can still pass in just a String based name but the underlying Map is MetricName ---> Metric [here](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricRegistry.java#L62)

**Comment by jiming** [comment]
Dear Ryantenney,

Thanks for your quick and detailed reply:)

Are you going to support aggregate the report for same metric name? Such as I would like to query the report for metric "accessApi" with follow condition:

1. accessApi: get total access count
2. accessApi(status=success): get total access count which were success
3. accessApi(status=failed): get total access count which were failed
4. accessApi(status=failed,source=web): get total access count which were failed and source is web



And one more important question, any plan for release date?

Have a nice day!
Jiming

**Comment by pgkaila** [comment]
@ryantenney  Can you please comment commit ID related to this issue/feature? I'm not able to find any commit for this issue.

Thanks,
Piyush

**Comment by gracew** [comment]
+1, this feature would be very useful for my work! do you have an estimated release date?

**Comment by arteam** [comment]
Support for tags is planned for the 5.0 version. Please see the discussion in #1175.

**Comment by shahbaaz31here** [comment]
Hey Folks,
Whether support for tags in already released ? I am unable to find any documentation on it.

Is it kept on hold for release ?

**Comment by joschi** [comment]
@shahbaaz31here See https://github.com/dropwizard/metrics/issues/1704.
