### ISSUE TITLE
Document thread-safety

### ISSUE THREAD

**Issue by cowwoc** [dropwizard/metrics#890]
I have read unofficial forum posts which hint that parts (or all) of the Metrics library is thread-safe but found no official documentation to back this up.

Please update the class-level Javadoc to indicate which classes are thread-safe. I assume that any classes that does not promise to be thread-safe, is not.

**Comment by randomstatistic** [comment]
+1
I spent some time digging through the code in order to satisfy myself that my highly multi-threaded usage based on SharedMetricsRegistries would work out ok.

**Comment by ryantenney** [comment]
The library is designed for use in large multithreaded applications, thread safety is of paramount importance. As such all classes are thread safe. I don't have the time to mark all classes as such (and I'm not sure I want to clutter the javadocs in that way). I would consider a 1-line addition to the documentation in order to clarify this issue.

**Comment by ryantenney** [comment]
Resolved by #913
