### ISSUE TITLE
Meter rates are not available in graphite / jmx / console reporter 

### ISSUE THREAD

**Issue by paphillon** [dropwizard/metrics#946]
When using a Meter metric the rates are always reported as 0.0, while count is displayed as it should. However when within code using 'meter.getOneMinuteRate();' or any other rate, the rate values are displayed. Is there anything I am missing?

Metric version: 3.1.2

**Comment by paphillon** [comment]
Can anyone help me with this? Any pointers? Anything I missed?

**Comment by ryanrupp** [comment]
Can you post the output of the console reporter for the meter where this is happening (or any/all meters). Also to clarify you're actively marking the meter? The rates will decay to 0 if there's no markings occurring however the count is a sum over the lifetime.

**Comment by paphillon** [comment]
Hi Thanks for the reply! The console reporter is configured to report every 500 millisecond and meter mark rate is at 1000 millisecond. As seen from the o/p the rates are always 0.00 and this is true for JMX as well as graphite reporters

```
            Meter meter = registry.meter(name("meter", "rate", "test"));
            while (true) {
                meter.mark();
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                }
            }
```

 Console O/P

```

-- Meters ----------------------------------------------------------------------
meter.rate.test
             count = 37
         mean rate = 0.00 events/millisecond
     1-minute rate = 0.00 events/millisecond
     5-minute rate = 0.00 events/millisecond
    15-minute rate = 0.00 events/millisecond

-- Meters ----------------------------------------------------------------------
meter.rate.test
             count = 38
         mean rate = 0.00 events/millisecond
     1-minute rate = 0.00 events/millisecond
     5-minute rate = 0.00 events/millisecond
    15-minute rate = 0.00 events/millisecond
```

**Comment by ryanrupp** [comment]
My initial guess is because your report is reporting rates as milliseconds the rate is going to be some small decimal given your test so it's truncating this in the console reporter because it's only reporting up to two decimal places (although I'm surprised this would be happening in the JMX reporter, it should be able to show doubles with deeper precision). Try changing the reported rate unit to minutes or seconds (the default is seconds) with the ConsoleReporter.Builder.convertRatesTo(TimeUnit.MINUTES)

**Comment by paphillon** [comment]
I tried the following reporting rates, but it's still 0.00. 

15, 30 Seconds
1 - Minute

<img width="385" alt="screen shot 2016-05-18 at 3 15 07 pm" src="https://cloud.githubusercontent.com/assets/8165433/15376685/752cd26c-1d0b-11e6-9e6d-d6fed95e29af.png">

it is strange, since I can see those values, when I step into during debug or just by using println with ```meter.getOneMinuteRate();```

**Comment by ryanrupp** [comment]
Did you try a different reporting rate unit though? **Note** this is different than how frequently the reporting reports the values, I mean on the meter it says RateUnit is "events/millisecond" which is too granular and may be truncating the precision of some decimal e.g. 0.0000001 events/millisecond. 

Wherever you have the ConsoleReporter built on the Builder use the method convertRatesTo and specify TimeUnit.MINUTES, right now you must be setting it to TimeUnit.MILLISECONDS.

The value you're seeing in the debugger when you call `meter.getOneMinuteRate()` is the rate per minute - but because you have the reporters setup to display the rate in **milliseconds**, it takes that number and multiplies it by the milliseconds conversion factor to report it in events/millisecond.

**Comment by paphillon** [comment]
Ah got you, will try it right away! Thanks

**Comment by paphillon** [comment]
Yes! That was it! Thanks a lot! I remember changing the mark rate, but I think that was too granular too. The JMX console that I am using is jvisualvm with JConsole MBean plugin which has similar precision settings as console / graphite reporters.

**Comment by ryantenney** [comment]
Great catch @ryanrupp, thanks!
