### ISSUE TITLE
Is the method MetricRegistry.getOrAdd() threadsafe?

### ISSUE THREAD

**Issue by ZhuzhuDing** [dropwizard/metrics#963]
Assume the metrics registry doesn't contain a counter named 'Count1'. 
When two threads get into this method simultaneously and call the method Map.get() return null.  Then they try to register one new instance under the given name respectively. One will create the counter 'Count1' successfully and the other will cause a IllegalArgumentException.

Am I right? Does this method getOrAdd() need to be synchronized?

**Comment by ryantenney** [comment]
You're right, but the 2nd thread will catch that IllegalArgumentException [here](https://github.com/dropwizard/metrics/blob/c309a8b55880dc6022e666e7c231d5a897f74140/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L318), retrieve the counter created by the 1st thread, and return it. Because of this and that the Map in use is a `ConcurrentHashMap`, synchronization is not required.
