### ISSUE TITLE
GraphiteReporter builder does not allow to set executor

### ISSUE THREAD

**Issue by jarek-przygodzki** [dropwizard/metrics#968]
When using Metrics GraphiteReporter in Java EE environment with [metrics-cdi](https://github.com/astefanutti/metrics-cdi) it's quite important to use executor service provided by the container

```
    @Inject
    private MetricRegistry metricRegistry;

    @Resource
    ManagedScheduledExecutorService executorService;

    GraphiteReporter reporter = GraphiteReporter.forRegistry(metricRegistry)
                                                      .withExecutor(executorService)
                                                      .build(graphite());
```

But as of now, GraphiteReporter builder does not allow to set executor  and neither does GraphiteReporter constructor.

**Comment by ryantenney** [comment]
Is it not sufficient to tie the reporter instance to the lifecycle by creating a @PreDestroy method to call `close()` on the reporter?

**Comment by svendiedrichsen** [comment]
I don't think it is sufficient to tie the reporter to the lifecycle of the @PreDestroy method because thus the ExecutorService as a resource cannot be managed by the container. You could make use of the administration and monitoring features of the container if you used the injected ExecutorService and allow for runtime parameter changes.
I suggest you take a look at changes #1018 from @vladimir-bukhtoyarov. They are pretty simple and straight forward.
